export const reporting:Record<string,string>={
  'Could not load reporting.':'No se pudieron cargar los informes.|Impossible de charger les rapports.|Die Berichte konnten nicht geladen werden.|Impossibile caricare i report.|De rapporten konden niet worden geladen.|Não foi possível carregar os relatórios.|Nie udało się wczytać raportów.|Nu s-au putut încărca rapoartele.|Přehledy se nepodařilo načíst.|Prehľady sa nepodarilo načítať.|Poročil ni bilo mogoče naložiti.|Nem sikerült betölteni a jelentéseket.|تعذر تحميل التقارير.',
  'Choose a reporting view.':'Elige una vista de informes.|Choisissez une vue des rapports.|Wählen Sie eine Berichtsansicht.|Scegli una vista dei report.|Kies een rapportweergave.|Escolha uma vista de relatórios.|Wybierz widok raportowania.|Alege o vizualizare a rapoartelor.|Vyberte zobrazení přehledů.|Vyberte zobrazenie prehľadov.|Izberite pogled poročil.|Válasszon jelentésnézetet.|اختر طريقة عرض التقارير.',
  'User activity':'Actividad del usuario|Activité utilisateur|Benutzeraktivität|Attività utente|Gebruikersactiviteit|Atividade do utilizador|Aktywność użytkownika|Activitatea utilizatorului|Aktivita uživatele|Aktivita používateľa|Dejavnost uporabnika|Felhasználói tevékenység|نشاط المستخدم',
  'Search by name, email or Workday ID':'Buscar por nombre, correo o ID de Workday|Rechercher par nom, e-mail ou identifiant Workday|Nach Name, E-Mail oder Workday-ID suchen|Cerca per nome, email o ID Workday|Zoek op naam, e-mail of Workday-ID|Pesquisar por nome, email ou ID Workday|Szukaj według imienia, e-maila lub ID Workday|Caută după nume, email sau ID Workday|Hledat podle jména, e-mailu nebo ID Workday|Hľadať podľa mena, e-mailu alebo ID Workday|Išči po imenu, e-pošti ali ID Workday|Keresés név, e-mail vagy Workday-azonosító alapján|ابحث بالاسم أو البريد الإلكتروني أو معرّف Workday',
  'Search for a user to view their training records.':'Busca un usuario para ver sus registros de formación.|Recherchez un utilisateur pour consulter ses formations.|Suchen Sie einen Benutzer, um seine Schulungsnachweise anzuzeigen.|Cerca un utente per visualizzare i suoi dati di formazione.|Zoek een gebruiker om diens opleidingsgegevens te bekijken.|Pesquise um utilizador para ver os seus registos de formação.|Wyszukaj użytkownika, aby wyświetlić jego szkolenia.|Caută un utilizator pentru a vedea înregistrările sale de instruire.|Vyhledejte uživatele a zobrazte jeho záznamy o školení.|Vyhľadajte používateľa a zobrazte jeho záznamy o školení.|Poiščite uporabnika za ogled njegovih evidenc usposabljanja.|Keressen egy felhasználót a képzési nyilvántartásának megtekintéséhez.|ابحث عن مستخدم لعرض سجلاته التدريبية.',
  'Page {page}':'Página {page}|Page {page}|Seite {page}|Pagina {page}|Pagina {page}|Página {page}|Strona {page}|Pagina {page}|Strana {page}|Strana {page}|Stran {page}|{page}. oldal|الصفحة {page}',
  'Check the search and page number.':'Comprueba la búsqueda y el número de página.|Vérifiez la recherche et le numéro de page.|Prüfen Sie die Suche und die Seitennummer.|Controlla la ricerca e il numero di pagina.|Controleer de zoekopdracht en het paginanummer.|Verifique a pesquisa e o número da página.|Sprawdź wyszukiwanie i numer strony.|Verifică căutarea și numărul paginii.|Zkontrolujte hledání a číslo stránky.|Skontrolujte vyhľadávanie a číslo strany.|Preverite iskanje in številko strani.|Ellenőrizze a keresést és az oldalszámot.|تحقق من البحث ورقم الصفحة.',
};
