// es | fr | de | it | nl | pt | pl | ro | cs | sk | sl | hu | ar
export const navigation:Record<string,string>={
'No matching courses.':'No hay cursos coincidentes.|Aucun cours correspondant.|Keine passenden Kurse.|Nessun corso corrispondente.|Geen overeenkomende cursussen.|Nenhum curso correspondente.|Brak pasujących kursów.|Niciun curs corespunzător.|Žádné odpovídající kurzy.|Žiadne zodpovedajúce kurzy.|Ni ustreznih tečajev.|Nincs megfelelő kurzus.|لا توجد دورات مطابقة.',
'Choose a store to assign courses.':'Elige una tienda para asignar cursos.|Choisissez un magasin pour attribuer des cours.|Wählen Sie eine Filiale, um Kurse zuzuweisen.|Scegli un negozio per assegnare i corsi.|Kies een winkel om cursussen toe te wijzen.|Escolha uma loja para atribuir cursos.|Wybierz sklep, aby przypisać kursy.|Alege un magazin pentru a atribui cursuri.|Vyberte prodejnu pro přiřazení kurzů.|Vyberte predajňu na priradenie kurzov.|Izberite trgovino za dodelitev tečajev.|Válasszon üzletet a kurzusok hozzárendeléséhez.|اختر متجرًا لتعيين الدورات.',

'Stores':'Tiendas|Magasins|Filialen|Negozi|Winkels|Lojas|Sklepy|Magazine|Prodejny|Predajne|Trgovine|Üzletek|المتاجر',
'Active':'Activo|Actif|Aktiv|Attivo|Actief|Ativo|Aktywny|Activ|Aktivní|Aktívne|Aktivno|Aktív|نشط',
'Choose a store.':'Elige una tienda.|Choisissez un magasin.|Wählen Sie eine Filiale.|Scegli un negozio.|Kies een winkel.|Escolha uma loja.|Wybierz sklep.|Alege un magazin.|Vyberte prodejnu.|Vyberte predajňu.|Izberite trgovino.|Válasszon üzletet.|اختر متجرًا.',

'Platform administration':'Administración de la plataforma|Administration de la plateforme|Plattformverwaltung|Amministrazione della piattaforma|Platformbeheer|Administração da plataforma|Administracja platformą|Administrarea platformei|Správa platformy|Správa platformy|Upravljanje platforme|Platformadminisztráció|إدارة المنصة',
'Manage Users':'Gestionar usuarios|Gérer les utilisateurs|Benutzer verwalten|Gestisci utenti|Gebruikers beheren|Gerir utilizadores|Zarządzaj użytkownikami|Gestionează utilizatorii|Spravovat uživatele|Spravovať používateľov|Upravljanje uporabnikov|Felhasználók kezelése|إدارة المستخدمين',
'Organisation':'Organización|Organisation|Organisation|Organizzazione|Organisatie|Organização|Organizacja|Organizație|Organizace|Organizácia|Organizacija|Szervezet|المؤسسة',
'Add store':'Añadir tienda|Ajouter un magasin|Filiale hinzufügen|Aggiungi negozio|Winkel toevoegen|Adicionar loja|Dodaj sklep|Adaugă magazin|Přidat prodejnu|Pridať predajňu|Dodaj trgovino|Üzlet hozzáadása|إضافة متجر',
'Search stores':'Buscar tiendas|Rechercher des magasins|Filialen suchen|Cerca negozi|Winkels zoeken|Pesquisar lojas|Szukaj sklepów|Caută magazine|Hledat prodejny|Hľadať predajne|Poišči trgovine|Üzletek keresése|البحث عن المتاجر',
'Archive this store? Training records are retained.':'¿Archivar esta tienda? Se conservan los registros de formación.|Archiver ce magasin ? Les dossiers de formation sont conservés.|Diese Filiale archivieren? Schulungsnachweise bleiben erhalten.|Archiviare questo negozio? I registri di formazione vengono conservati.|Deze winkel archiveren? Opleidingsgegevens blijven bewaard.|Arquivar esta loja? Os registos de formação são mantidos.|Zarchiwizować ten sklep? Dokumentacja szkoleniowa zostanie zachowana.|Arhivezi acest magazin? Evidențele de instruire sunt păstrate.|Archivovat tuto prodejnu? Záznamy o školení zůstanou zachovány.|Archivovať túto predajňu? Záznamy o školení zostanú zachované.|Arhivirati to trgovino? Evidence usposabljanja se ohranijo.|Archiválja ezt az üzletet? A képzési nyilvántartások megmaradnak.|هل تريد أرشفة هذا المتجر؟ تُحفظ سجلات التدريب.',
'Archive store':'Archivar tienda|Archiver le magasin|Filiale archivieren|Archivia negozio|Winkel archiveren|Arquivar loja|Archiwizuj sklep|Arhivează magazinul|Archivovat prodejnu|Archivovať predajňu|Arhiviraj trgovino|Üzlet archiválása|أرشفة المتجر',
'Archived':'Archivado|Archivé|Archiviert|Archiviato|Gearchiveerd|Arquivado|Zarchiwizowany|Arhivat|Archivováno|Archivované|Arhivirano|Archivált|مؤرشف',
'Archive':'Archivar|Archiver|Archivieren|Archivia|Archiveren|Arquivar|Archiwizuj|Arhivează|Archivovat|Archivovať|Arhiviraj|Archiválás|أرشفة',
'Restore':'Restaurar|Restaurer|Wiederherstellen|Ripristina|Herstellen|Restaurar|Przywróć|Restaurează|Obnovit|Obnoviť|Obnovi|Visszaállítás|استعادة',
'Check the store name and country.':'Comprueba el nombre de la tienda y el país.|Vérifiez le nom du magasin et le pays.|Prüfen Sie den Filialnamen und das Land.|Controlla il nome del negozio e il paese.|Controleer de winkelnaam en het land.|Verifique o nome da loja e o país.|Sprawdź nazwę sklepu i kraj.|Verifică numele magazinului și țara.|Zkontrolujte název prodejny a zemi.|Skontrolujte názov predajne a krajinu.|Preverite ime trgovine in državo.|Ellenőrizze az üzlet nevét és az országot.|تحقق من اسم المتجر والبلد.',
'This store already exists.':'Esta tienda ya existe.|Ce magasin existe déjà.|Diese Filiale existiert bereits.|Questo negozio esiste già.|Deze winkel bestaat al.|Esta loja já existe.|Ten sklep już istnieje.|Acest magazin există deja.|Tato prodejna již existuje.|Táto predajňa už existuje.|Ta trgovina že obstaja.|Ez az üzlet már létezik.|هذا المتجر موجود بالفعل.',
};
