export const recognitionCopy:Record<string,string>={
 "Manage training exemptions and prior learning": "Gestionar exenciones y aprendizaje previo|Gérer les dispenses et les acquis|Befreiungen und Vorwissen verwalten|Gestisci esenzioni e apprendimento pregresso|Vrijstellingen en eerder leren beheren|Gerir dispensas e aprendizagem anterior|Zarządzaj zwolnieniami i wcześniejszą nauką|Gestionați scutirile și învățarea anterioară|Správa výjimek a předchozího vzdělání|Správa výnimiek a predchádzajúceho vzdelania|Upravljanje oprostitev in predhodnega znanja|Mentességek és korábbi tanulás kezelése|إدارة الإعفاءات والتعلم السابق",
 "Training decision saved.": "Decisión guardada.|Décision enregistrée.|Entscheidung gespeichert.|Decisione salvata.|Besluit opgeslagen.|Decisão guardada.|Decyzja zapisana.|Decizie salvată.|Rozhodnutí uloženo.|Rozhodnutie uložené.|Odločitev shranjena.|Döntés mentve.|تم حفظ القرار.",
 "Training exemptions and prior learning": "Exenciones de formación y aprendizaje previo|Dispenses de formation et acquis|Schulungsbefreiungen und Vorwissen|Esenzioni dalla formazione e apprendimento pregresso|Trainingsvrijstellingen en eerder leren|Dispensas de formação e aprendizagem anterior|Zwolnienia ze szkoleń i wcześniejsza nauka|Scutiri de formare și învățare anterioară|Výjimky ze školení a předchozí vzdělání|Výnimky zo školení a predchádzajúce vzdelanie|Oprostitve usposabljanja in predhodno znanje|Képzési mentességek és korábbi tanulás|الإعفاءات من التدريب والتعلم السابق",
 "Search learners and courses": "Buscar alumnos y cursos|Rechercher des apprenants et des cours|Lernende und Kurse suchen|Cerca studenti e corsi|Cursisten en cursussen zoeken|Pesquisar formandos e cursos|Szukaj uczestników i kursów|Căutați cursanți și cursuri|Hledat účastníky a kurzy|Hľadať účastníkov a kurzy|Poišči udeležence in tečaje|Tanulók és kurzusok keresése|البحث عن المتعلمين والدورات",
 "Evidence reference": "Referencia de evidencia|Référence du justificatif|Nachweisreferenz|Riferimento della prova|Bewijsreferentie|Referência da evidência|Odnośnik do dowodu|Referință dovadă|Odkaz na doklad|Odkaz na doklad|Sklic na dokazilo|Bizonyíték hivatkozása|مرجع الدليل",
 "Approved by": "Aprobado por|Approuvé par|Genehmigt von|Approvato da|Goedgekeurd door|Aprovado por|Zatwierdził|Aprobat de|Schválil|Schválil|Odobril|Jóváhagyta|تمت الموافقة بواسطة",
 "Revoke decision": "Revocar decisión|Révoquer la décision|Entscheidung widerrufen|Revoca decisione|Besluit intrekken|Revogar decisão|Cofnij decyzję|Revocați decizia|Odvolat rozhodnutí|Odvolať rozhodnutie|Prekliči odločitev|Döntés visszavonása|إلغاء القرار",
 "Record decision": "Registrar decisión|Enregistrer une décision|Entscheidung erfassen|Registra decisione|Besluit vastleggen|Registar decisão|Zapisz decyzję|Înregistrați decizia|Zaznamenat rozhodnutí|Zaznamenať rozhodnutie|Zabeleži odločitev|Döntés rögzítése|تسجيل القرار",
 "Decision": "Decisión|Décision|Entscheidung|Decisione|Besluit|Decisão|Decyzja|Decizie|Rozhodnutí|Rozhodnutie|Odločitev|Döntés|القرار",
 "Temporary exemption": "Exención temporal|Dispense temporaire|Befristete Befreiung|Esenzione temporanea|Tijdelijke vrijstelling|Dispensa temporária|Tymczasowe zwolnienie|Scutire temporară|Dočasná výjimka|Dočasná výnimka|Začasna oprostitev|Ideiglenes mentesség|إعفاء مؤقت",
 "Recognised prior learning": "Aprendizaje previo reconocido|Acquis reconnus|Anerkanntes Vorwissen|Apprendimento pregresso riconosciuto|Erkend eerder leren|Aprendizagem anterior reconhecida|Uznana wcześniejsza nauka|Învățare anterioară recunoscută|Uznané předchozí vzdělání|Uznané predchádzajúce vzdelanie|Priznano predhodno znanje|Elismert korábbi tanulás|التعلم السابق المعترف به",
 "Deadline extension": "Ampliación de plazo|Prolongation du délai|Fristverlängerung|Proroga della scadenza|Termijnverlenging|Prorrogação do prazo|Przedłużenie terminu|Prelungirea termenului|Prodloužení termínu|Predĺženie termínu|Podaljšanje roka|Határidő-hosszabbítás|تمديد الموعد النهائي",
 "Qualification or external training": "Cualificación o formación externa|Qualification ou formation externe|Qualifikation oder externe Schulung|Qualifica o formazione esterna|Kwalificatie of externe training|Qualificação ou formação externa|Kwalifikacja lub szkolenie zewnętrzne|Calificare sau formare externă|Kvalifikace nebo externí školení|Kvalifikácia alebo externé školenie|Kvalifikacija ali zunanje usposabljanje|Képesítés vagy külső képzés|المؤهل أو التدريب الخارجي",
 "Award date": "Fecha de obtención|Date d’obtention|Erwerbsdatum|Data di conseguimento|Datum van behalen|Data de obtenção|Data uzyskania|Data obținerii|Datum získání|Dátum získania|Datum pridobitve|Megszerzés dátuma|تاريخ الحصول",
 "New deadline": "Nuevo plazo|Nouvelle échéance|Neue Frist|Nuova scadenza|Nieuwe deadline|Novo prazo|Nowy termin|Termen nou|Nový termín|Nový termín|Novi rok|Új határidő|الموعد النهائي الجديد",
 "Valid until": "Válido hasta|Valable jusqu’au|Gültig bis|Valido fino al|Geldig tot|Válido até|Ważne do|Valabil până la|Platné do|Platné do|Velja do|Érvényes eddig|صالح حتى",
 "Certificate reference or secure document location": "Referencia del certificado o ubicación segura del documento|Référence du certificat ou emplacement sécurisé du document|Zertifikatsreferenz oder sicherer Dokumentenablageort|Riferimento del certificato o posizione sicura del documento|Certificaatreferentie of veilige documentlocatie|Referência do certificado ou localização segura do documento|Numer certyfikatu lub bezpieczna lokalizacja dokumentu|Referință certificat sau locație securizată a documentului|Odkaz na certifikát nebo bezpečné umístění dokumentu|Odkaz na certifikát alebo bezpečné umiestnenie dokumentu|Sklic na potrdilo ali varno mesto dokumenta|Tanúsítvány hivatkozása vagy biztonságos dokumentumhely|مرجع الشهادة أو موقع المستند الآمن",
 "Save decision": "Guardar decisión|Enregistrer la décision|Entscheidung speichern|Salva decisione|Besluit opslaan|Guardar decisão|Zapisz decyzję|Salvați decizia|Uložit rozhodnutí|Uložiť rozhodnutie|Shrani odločitev|Döntés mentése|حفظ القرار",
 "Exempt": "Exento|Dispensé|Befreit|Esente|Vrijgesteld|Dispensado|Zwolniony|Scutit|Osvobozeno|Oslobodené|Oproščeno|Mentesített|معفى",
 "Prior learning recognised": "Aprendizaje previo reconocido|Acquis reconnus|Vorwissen anerkannt|Apprendimento pregresso riconosciuto|Eerder leren erkend|Aprendizagem anterior reconhecida|Wcześniejsza nauka uznana|Învățare anterioară recunoscută|Předchozí vzdělání uznáno|Predchádzajúce vzdelanie uznané|Predhodno znanje priznano|Korábbi tanulás elismerve|تم الاعتراف بالتعلم السابق",
 "Deadline extended": "Plazo ampliado|Délai prolongé|Frist verlängert|Scadenza prorogata|Termijn verlengd|Prazo prorrogado|Termin przedłużony|Termen prelungit|Termín prodloužen|Termín predĺžený|Rok podaljšan|Határidő meghosszabbítva|تم تمديد الموعد النهائي",
 "A reason, evidence reference and expiry date are required.": "Se requiere motivo, referencia de evidencia y fecha de caducidad.|Un motif, une référence de justificatif et une date d’expiration sont requis.|Grund, Nachweisreferenz und Ablaufdatum sind erforderlich.|Sono richiesti motivo, riferimento della prova e data di scadenza.|Een reden, bewijsreferentie en vervaldatum zijn vereist.|São necessários motivo, referência da evidência e data de validade.|Wymagane są powód, odnośnik do dowodu i data ważności.|Sunt necesare un motiv, o referință de dovadă și o dată de expirare.|Je vyžadován důvod, odkaz na doklad a datum vypršení.|Vyžaduje sa dôvod, odkaz na doklad a dátum skončenia platnosti.|Potrebni so razlog, sklic na dokazilo in datum poteka.|Indoklás, bizonyítékhivatkozás és lejárati dátum szükséges.|يلزم تقديم السبب ومرجع الدليل وتاريخ الانتهاء.",
 "Feature off. Existing decisions remain valid and can be revoked.": "Función desactivada. Las decisiones existentes siguen siendo válidas y pueden revocarse.|Fonction désactivée. Les décisions existantes restent valables et peuvent être révoquées.|Funktion aus. Bestehende Entscheidungen bleiben gültig und können widerrufen werden.|Funzione disattivata. Le decisioni esistenti restano valide e possono essere revocate.|Functie uit. Bestaande besluiten blijven geldig en kunnen worden ingetrokken.|Funcionalidade desativada. As decisões existentes permanecem válidas e podem ser revogadas.|Funkcja wyłączona. Istniejące decyzje pozostają ważne i można je cofnąć.|Funcție dezactivată. Deciziile existente rămân valabile și pot fi revocate.|Funkce vypnuta. Stávající rozhodnutí zůstávají platná a lze je odvolat.|Funkcia vypnutá. Existujúce rozhodnutia zostávajú platné a možno ich odvolať.|Funkcija izklopljena. Obstoječe odločitve ostanejo veljavne in jih je mogoče preklicati.|Funkció kikapcsolva. A meglévő döntések érvényesek maradnak és visszavonhatók.|الميزة معطلة. تبقى القرارات الحالية صالحة ويمكن إلغاؤها.",
 "Exemptions are excluded from compliance. Prior learning counts as compliant. Certificates and pathways still require course completion.": "Las exenciones se excluyen del cumplimiento. El aprendizaje previo cuenta como conforme. Los certificados y los itinerarios siguen requiriendo completar el curso.|Les dispenses sont exclues de la conformité. Les acquis comptent comme conformes. Les certificats et parcours nécessitent toujours la réussite du cours.|Befreiungen werden aus der Compliance ausgeschlossen. Vorwissen zählt als konform. Zertifikate und Lernpfade erfordern weiterhin den Kursabschluss.|Le esenzioni sono escluse dalla conformità. L’apprendimento pregresso conta come conforme. Certificati e percorsi richiedono comunque il completamento del corso.|Vrijstellingen worden uitgesloten van naleving. Eerder leren telt als voldaan. Certificaten en leerpaden vereisen nog steeds cursusvoltooiing.|As dispensas são excluídas da conformidade. A aprendizagem anterior conta como conforme. Certificados e percursos continuam a exigir a conclusão do curso.|Zwolnienia są wyłączone ze zgodności. Wcześniejsza nauka liczy się jako zgodna. Certyfikaty i ścieżki nadal wymagają ukończenia kursu.|Scutirile sunt excluse din conformitate. Învățarea anterioară contează ca fiind conformă. Certificatele și parcursurile necesită în continuare finalizarea cursului.|Výjimky se nezahrnují do souladu. Předchozí vzdělání se počítá jako splněné. Certifikáty a vzdělávací cesty stále vyžadují dokončení kurzu.|Výnimky sa nezahŕňajú do súladu. Predchádzajúce vzdelanie sa počíta ako splnené. Certifikáty a vzdelávacie cesty stále vyžadujú dokončenie kurzu.|Oprostitve so izključene iz skladnosti. Predhodno znanje šteje kot skladno. Potrdila in učne poti še vedno zahtevajo dokončanje tečaja.|A mentességek nem számítanak bele a megfelelőségbe. A korábbi tanulás megfelelőnek számít. A tanúsítványokhoz és tanulási utakhoz továbbra is szükséges a kurzus elvégzése.|تُستبعد الإعفاءات من حساب الامتثال. يُحسب التعلم السابق كامتثال. لا تزال الشهادات ومسارات التعلم تتطلب إكمال الدورة."
};

recognitionCopy["Training exemptions and recognised prior learning"]=recognitionCopy["Training exemptions and prior learning"];
