export const storeDetails:Record<string,string>={
'Edit':'Editar|Modifier|Bearbeiten|Modifica|Bewerken|Editar|Edytuj|Editează|Upravit|Upraviť|Uredi|Szerkesztés|تعديل',
'Save changes':'Guardar cambios|Enregistrer les modifications|Änderungen speichern|Salva modifiche|Wijzigingen opslaan|Guardar alterações|Zapisz zmiany|Salvează modificările|Uložit změny|Uložiť zmeny|Shrani spremembe|Módosítások mentése|حفظ التغييرات',
'Store details':'Detalles de la tienda|Détails du magasin|Filialdetails|Dettagli negozio|Winkelgegevens|Detalhes da loja|Dane sklepu|Detalii magazin|Podrobnosti prodejny|Podrobnosti predajne|Podrobnosti trgovine|Üzlet adatai|تفاصيل المتجر',
'Store updated.':'Tienda actualizada.|Magasin mis à jour.|Filiale aktualisiert.|Negozio aggiornato.|Winkel bijgewerkt.|Loja atualizada.|Sklep zaktualizowany.|Magazin actualizat.|Prodejna aktualizována.|Predajňa aktualizovaná.|Trgovina posodobljena.|Üzlet frissítve.|تم تحديث المتجر.',
'Number of learners':'Número de alumnos|Nombre d’apprenants|Anzahl der Lernenden|Numero di partecipanti|Aantal cursisten|Número de formandos|Liczba uczestników|Număr de cursanți|Počet účastníků|Počet účastníkov|Število udeležencev|Tanulók száma|عدد المتعلمين',
'Active learners only.':'Solo alumnos activos.|Apprenants actifs uniquement.|Nur aktive Lernende.|Solo partecipanti attivi.|Alleen actieve cursisten.|Apenas formandos ativos.|Tylko aktywni uczestnicy.|Doar cursanți activi.|Pouze aktivní účastníci.|Iba aktívni účastníci.|Samo aktivni udeleženci.|Csak aktív tanulók.|المتعلمون النشطون فقط.',
'Store contact only. Manage account access in Manage users.':'Solo contacto de la tienda. Gestiona el acceso en Gestionar usuarios.|Contact du magasin uniquement. Gérez les accès dans Gérer les utilisateurs.|Nur Filialkontakt. Kontozugriff unter Benutzer verwalten einstellen.|Solo contatto del negozio. Gestisci gli accessi in Gestisci utenti.|Alleen winkelcontact. Beheer toegang via Gebruikers beheren.|Apenas contacto da loja. Gira o acesso em Gerir utilizadores.|Tylko kontakt sklepu. Zarządzaj dostępem w Zarządzaj użytkownikami.|Doar contactul magazinului. Gestionează accesul în Gestionare utilizatori.|Pouze kontakt prodejny. Přístup spravujte v části Správa uživatelů.|Iba kontakt predajne. Prístup spravujte v časti Správa používateľov.|Samo kontakt trgovine. Dostop upravljajte v Upravljanju uporabnikov.|Csak az üzlet kapcsolattartója. A hozzáférést a Felhasználók kezelése oldalon állítsa be.|جهة اتصال المتجر فقط. أدر الوصول إلى الحساب في إدارة المستخدمين.',
'This store changed. Close and reopen its details.':'Esta tienda ha cambiado. Cierra y vuelve a abrir sus detalles.|Ce magasin a été modifié. Fermez et rouvrez ses détails.|Diese Filiale wurde geändert. Details schließen und erneut öffnen.|Questo negozio è stato modificato. Chiudi e riapri i dettagli.|Deze winkel is gewijzigd. Sluit en heropen de gegevens.|Esta loja foi alterada. Feche e reabra os detalhes.|Ten sklep został zmieniony. Zamknij i otwórz ponownie jego dane.|Acest magazin a fost modificat. Închide și redeschide detaliile.|Tato prodejna byla změněna. Zavřete a znovu otevřete podrobnosti.|Táto predajňa bola zmenená. Zatvorte a znovu otvorte podrobnosti.|Ta trgovina je bila spremenjena. Zaprite in znova odprite podrobnosti.|Az üzlet adatai megváltoztak. Zárja be és nyissa meg újra az adatlapot.|تم تغيير هذا المتجر. أغلق التفاصيل وأعد فتحها.',
};
