// Order: es, fr, de, it, nl, pt, pl, ro, cs, sk, sl, hu, ar.
export const login:Record<string,string>={
'Enter a valid Workday ID.':'Introduce un ID de Workday válido.|Saisissez un identifiant Workday valide.|Geben Sie eine gültige Workday-ID ein.|Inserisci un ID Workday valido.|Voer een geldige Workday-ID in.|Introduza um ID Workday válido.|Wpisz prawidłowy identyfikator Workday.|Introdu un ID Workday valid.|Zadejte platné Workday ID.|Zadajte platné Workday ID.|Vnesite veljaven ID Workday.|Adjon meg érvényes Workday-azonosítót.|أدخل معرّف Workday صالحًا.',
'This Workday ID is already linked to an account. Choose Login to continue.':'Este ID de Workday ya está vinculado a una cuenta. Inicia sesión para continuar.|Cet identifiant Workday est déjà associé à un compte. Connectez-vous pour continuer.|Diese Workday-ID ist bereits mit einem Konto verknüpft. Melden Sie sich an.|Questo ID Workday è già collegato a un account. Accedi per continuare.|Deze Workday-ID is al aan een account gekoppeld. Log in om door te gaan.|Este ID Workday já está associado a uma conta. Inicie sessão para continuar.|Ten identyfikator Workday jest już powiązany z kontem. Zaloguj się, aby kontynuować.|Acest ID Workday este deja asociat unui cont. Autentifică-te pentru a continua.|Toto Workday ID je již propojeno s účtem. Pokračujte přihlášením.|Toto Workday ID je už prepojené s účtom. Pokračujte prihlásením.|Ta ID Workday je že povezan z računom. Za nadaljevanje se prijavite.|Ez a Workday-azonosító már egy fiókhoz tartozik. A folytatáshoz jelentkezzen be.|معرّف Workday هذا مرتبط بحساب بالفعل. سجّل الدخول للمتابعة.',
'Email, Workday ID or access code':'Correo, ID de Workday o código de acceso|E-mail, identifiant Workday ou code d’accès|E-Mail, Workday-ID oder Zugangscode|E-mail, ID Workday o codice di accesso|E-mail, Workday-ID of toegangscode|E-mail, ID Workday ou código de acesso|E-mail, identyfikator Workday lub kod dostępu|E-mail, ID Workday sau cod de acces|E-mail, Workday ID nebo přístupový kód|E-mail, Workday ID alebo prístupový kód|E-pošta, ID Workday ali koda za dostop|E-mail, Workday-azonosító vagy belépési kód|البريد الإلكتروني أو معرّف Workday أو رمز الدخول',
'Enter your email, Workday ID or access code and password.':'Introduce tu correo, ID de Workday o código de acceso y contraseña.|Saisissez votre e-mail, identifiant Workday ou code d’accès et votre mot de passe.|Geben Sie Ihre E-Mail, Workday-ID oder Ihren Zugangscode und Ihr Passwort ein.|Inserisci e-mail, ID Workday o codice di accesso e password.|Voer je e-mail, Workday-ID of toegangscode en wachtwoord in.|Introduza o e-mail, ID Workday ou código de acesso e a palavra-passe.|Wpisz e-mail, identyfikator Workday lub kod dostępu oraz hasło.|Introdu e-mailul, ID-ul Workday sau codul de acces și parola.|Zadejte e-mail, Workday ID nebo přístupový kód a heslo.|Zadajte e-mail, Workday ID alebo prístupový kód a heslo.|Vnesite e-pošto, ID Workday ali kodo za dostop in geslo.|Adja meg e-mail-címét, Workday-azonosítóját vagy belépési kódját és jelszavát.|أدخل بريدك الإلكتروني أو معرّف Workday أو رمز الدخول وكلمة المرور.',
'Legacy access code':'Código de acceso anterior|Ancien code d’accès|Bisheriger Zugangscode|Codice di accesso precedente|Oude toegangscode|Código de acesso anterior|Dotychczasowy kod dostępu|Cod de acces anterior|Původní přístupový kód|Pôvodný prístupový kód|Prejšnja koda za dostop|Korábbi belépési kód|رمز الدخول السابق',
'Not recorded':'No registrado|Non renseigné|Nicht erfasst|Non registrato|Niet vastgelegd|Não registado|Nie zapisano|Neînregistrat|Neevidováno|Neevidované|Ni zabeleženo|Nincs rögzítve|غير مسجّل',
'Add your email address':'Añade tu correo electrónico|Ajoutez votre adresse e-mail|E-Mail-Adresse hinzufügen|Aggiungi il tuo indirizzo e-mail|Voeg je e-mailadres toe|Adicione o seu endereço de e-mail|Dodaj swój adres e-mail|Adaugă adresa de e-mail|Přidejte svou e-mailovou adresu|Pridajte svoju e-mailovú adresu|Dodajte svoj e-poštni naslov|Adja meg e-mail-címét|أضف عنوان بريدك الإلكتروني',
'To continue, enter an email address that is not already linked to another account.':'Para continuar, introduce un correo que no esté vinculado a otra cuenta.|Pour continuer, saisissez une adresse e-mail qui n’est pas déjà associée à un autre compte.|Geben Sie zum Fortfahren eine E-Mail-Adresse ein, die noch nicht mit einem anderen Konto verknüpft ist.|Per continuare, inserisci un indirizzo e-mail non già collegato a un altro account.|Voer een e-mailadres in dat nog niet aan een ander account is gekoppeld om door te gaan.|Para continuar, introduza um e-mail que ainda não esteja associado a outra conta.|Aby kontynuować, wpisz adres e-mail, który nie jest powiązany z innym kontem.|Pentru a continua, introdu o adresă de e-mail care nu este deja asociată altui cont.|Pro pokračování zadejte e-mailovou adresu, která není propojena s jiným účtem.|Ak chcete pokračovať, zadajte e-mailovú adresu, ktorá nie je prepojená s iným účtom.|Za nadaljevanje vnesite e-poštni naslov, ki še ni povezan z drugim računom.|A folytatáshoz adjon meg olyan e-mail-címet, amely még nincs másik fiókhoz kapcsolva.|للمتابعة، أدخل عنوان بريد إلكتروني غير مرتبط بحساب آخر.',
'Save and continue':'Guardar y continuar|Enregistrer et continuer|Speichern und fortfahren|Salva e continua|Opslaan en doorgaan|Guardar e continuar|Zapisz i kontynuuj|Salvează și continuă|Uložit a pokračovat|Uložiť a pokračovať|Shrani in nadaljuj|Mentés és folytatás|حفظ ومتابعة',
'This email is already registered. Use a different email address.':'Este correo ya está registrado. Usa otro correo electrónico.|Cette adresse e-mail est déjà enregistrée. Utilisez une autre adresse.|Diese E-Mail-Adresse ist bereits registriert. Verwenden Sie eine andere Adresse.|Questa e-mail è già registrata. Usa un altro indirizzo.|Dit e-mailadres is al geregistreerd. Gebruik een ander e-mailadres.|Este e-mail já está registado. Utilize outro endereço.|Ten e-mail jest już zarejestrowany. Użyj innego adresu.|Acest e-mail este deja înregistrat. Folosește altă adresă.|Tento e-mail je již registrován. Použijte jinou adresu.|Tento e-mail je už registrovaný. Použite inú adresu.|Ta e-poštni naslov je že registriran. Uporabite drug naslov.|Ez az e-mail-cím már regisztrálva van. Használjon másik címet.|هذا البريد الإلكتروني مسجّل بالفعل. استخدم عنوانًا آخر.',
'Your sign-in expired. Please log in again.':'Tu sesión ha caducado. Vuelve a iniciar sesión.|Votre connexion a expiré. Reconnectez-vous.|Ihre Anmeldung ist abgelaufen. Melden Sie sich erneut an.|La sessione è scaduta. Accedi di nuovo.|Je aanmelding is verlopen. Log opnieuw in.|A sua sessão expirou. Inicie sessão novamente.|Sesja wygasła. Zaloguj się ponownie.|Sesiunea a expirat. Autentifică-te din nou.|Vaše přihlášení vypršelo. Přihlaste se znovu.|Vaše prihlásenie vypršalo. Prihláste sa znova.|Vaša prijava je potekla. Prijavite se znova.|A bejelentkezése lejárt. Jelentkezzen be újra.|انتهت صلاحية تسجيل الدخول. سجّل الدخول مجددًا.',
};
