// The named sample-account data migration is covered separately by sample-completion-check.mjs.
import assert from 'node:assert/strict';
import {readFileSync,readdirSync,mkdtempSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {AsyncLocalStorage} from 'node:async_hooks';
import {PGlite} from '@electric-sql/pglite';
import {build} from 'esbuild';
const pg=new PGlite();
const migrations=readdirSync('netlify/database/migrations').sort().filter(name=>name!=='20261009160000_sample-learner-induction-completion');
const migration=migrations.find(n=>n.endsWith('_period-credits'));
for(const n of migrations.filter(n=>n<migration))await pg.exec(readFileSync(`netlify/database/migrations/${n}/migration.sql`,'utf8'));
await pg.exec(`INSERT INTO learners(id,name,email,code_hash,store_id,country,entered_at) VALUES('existing','Existing learner','existing@test.invalid','unused','legacy-store','Ireland','2026-10-01');
 INSERT INTO courses(id,title,audience_json,created_at,updated_at) VALUES('existing-course','Existing course','{}','2026-10-01','2026-10-01');
 INSERT INTO course_assignments VALUES('existing','existing-course','original manager','2026-10-01T00:00:00Z');`);
await pg.exec(readFileSync(`netlify/database/migrations/${migration}/migration.sql`,'utf8'));
for(const n of migrations.filter(n=>n>migration))await pg.exec(readFileSync(`netlify/database/migrations/${n}/migration.sql`,'utf8'));
const context=new AsyncLocalStorage();
const pool={async query(sql,args=[]){const r=await pg.query(sql,args);return {rows:r.rows,rowCount:r.affectedRows};},async connect(){return {...this,release(){}};}};
globalThis.__creditTest={pool,identity:()=>context.getStore()?.admin?{email:'platform@test.invalid'}:null,cookie:()=>context.getStore()?.user||''};
const dir=mkdtempSync(join(tmpdir(),'primark-credit-check-')),entry=join(dir,'entry.ts');
writeFileSync(entry,`export * as report from '${process.cwd()}/lib/training-report.ts';
 export * as assessor from '${process.cwd()}/app/api/assessor/route.ts';
 export * as renew from '${process.cwd()}/app/api/courses/renew/route.ts';
 export * as courses from '${process.cwd()}/app/api/courses/route.ts';
 export * as admin from '${process.cwd()}/app/api/admin/courses/route.ts';
 export * as runtime from '${process.cwd()}/app/api/scorm/route.ts';
 export * as renewal from '${process.cwd()}/lib/course-renewals.ts';
 export {renewalDays} from '${process.cwd()}/lib/course-renewal-status.ts';
 export {hash} from '${process.cwd()}/lib/server.ts';`);
await build({entryPoints:[entry],outfile:join(dir,'bundle.mjs'),bundle:true,platform:'node',format:'esm',tsconfig:'tsconfig.json',plugins:[{name:'test',setup(b){
 b.onResolve({filter:/^@netlify\/database$/},()=>({path:'db',namespace:'test'}));
 b.onResolve({filter:/^@\/lib\/admin-auth$/},()=>({path:'auth',namespace:'test'}));
 b.onResolve({filter:/^next\/headers$/},()=>({path:'cookies',namespace:'test'}));
 b.onResolve({filter:/^next\/server$/},()=>({path:'next',namespace:'test'}));
 b.onLoad({filter:/.*/,namespace:'test'},a=>({contents:a.path==='db'?'export const getDatabase=()=>({pool:globalThis.__creditTest.pool});':a.path==='auth'?'export const getAdminUser=async()=>globalThis.__creditTest.identity();export const credentials=()=>null;':a.path==='cookies'?"export const cookies=async()=>({get:n=>n==='primark_session'&&globalThis.__creditTest.cookie()?{value:globalThis.__creditTest.cookie()}:undefined});":'export class NextRequest extends Request {}; export const NextResponse=Response;',loader:'js'}));
}}]});
const m=await import(join(dir,'bundle.mjs'));let checks=0;
const q=async(sql,...args)=>(await pg.query(sql,args)).rows;
const one=async(sql,...args)=>(await q(sql,...args))[0];
async function check(name,fn){await fn();console.log('PASS '+name);checks++;}
async function call(mod,method,path,body,{user='',admin=false,origin='https://local.test'}={}){return context.run({user,admin},async()=>{const req=new Request('https://local.test'+path,{method,headers:{'Content-Type':'application/json',Origin:origin,...(user?{Cookie:'primark_session='+user}:{})},...(body?{body:JSON.stringify(body)}:{})});req.nextUrl=new URL(req.url);req.cookies={get:n=>n==='primark_session'&&user?{value:user}:undefined};return mod[method](req);});}
const person=async(id,store='credit-ie',country='Ireland')=>{await q('INSERT INTO learners(id,name,email,code_hash,store_id,country,entered_at) VALUES($1,$1,$2,$1,$3,$4,$5)',id,id+'@test.invalid',store,country,new Date().toISOString());await q('INSERT INTO sessions VALUES($1,$2,$3)',await m.hash(id),id,'2099-01-01');};
async function course(id,audience={countries:[],sites:[],users:[]}){await q("INSERT INTO courses(id,title,status,audience_json,created_at,updated_at,catalogue_scope,validity_months) VALUES($1,$1,'published',$2,'2026-01-01','2026-01-01','global',12)",id,JSON.stringify(audience));await q("INSERT INTO course_packages(id,course_id,filename,status,scos_json,file_count,total_bytes,created_at) VALUES($1,$2,'fixture.zip','ready',$3,1,10,'2026-01-01')",id+'-pack',id,JSON.stringify([{id:'sco',title:'Lesson',href:'index.html',mastery:'',launchData:''}]));await q('UPDATE courses SET package_id=$2 WHERE id=$1',id,id+'-pack');}
const assign=async(id,cid,at=new Date().toISOString(),renew=false)=>one('SELECT assign_credit_course($1,$2,$3,$4::timestamptz,$5) AS added',id,cid,'manager@test.invalid',at,renew);
const history=async(id,cid)=>one('SELECT h.* FROM course_assignments a JOIN assignment_history h ON h.id=a.history_id WHERE a.learner_id=$1 AND a.course_id=$2',id,cid);
const balance=async(store='credit-ie')=>(await one('SELECT balance FROM store_credit_accounts WHERE store_id=$1',store)).balance;
try{
 await q('UPDATE organisation_settings SET credits_enabled=false');
 for(const id of ['student','assessor','wrong','expired','self','external'])await person(id);
 await course('practical');await course('ordinary');
 await assign('student','ordinary');
 await q("UPDATE courses SET assessor_required=true WHERE id IN ('ordinary','practical')");
 assert.equal((await history('student','ordinary')).assessor_required,false);
 await assign('student','practical');const h=await history('student','practical');
 assert.equal(h.assessor_required,true);
 await q("INSERT INTO assessor_accounts VALUES('external',true),('assessor',false),('wrong',false),('expired',false),('self',false)");
 assert.equal((await assign('external','ordinary')).added,false);
 const grant=async(id,site='*',expires=null)=>q('INSERT INTO assessor_grants(id,learner_id,course_id,site_id,qualification,expires_on,assigned_by) VALUES($1,$1,\'practical\',$2,\'Qualified trainer\',$3,\'admin\')',id,site,expires);
 await grant('assessor');await grant('wrong','other-site');await grant('expired','*','2000-01-01');await grant('self');
 const today=new Date().toISOString().slice(0,10);
 const assessment=(user,extra={})=>call(m.assessor,'POST','/api/assessor',{action:'assess',id:h.id,date:today,outcome:'pass',declaration:true,notes:'',...extra},{user});
 assert.equal((await assessment('assessor')).status,400);
 await q("INSERT INTO scorm_progress(learner_id,package_id,sco_id,status,completed_at,updated_at) VALUES('student','practical-pack','sco','passed',$1,$1)",today+'T01:00:00.000Z');
 await q("SELECT issue_course_certificate('student','practical-pack')");
 assert.equal((await q("SELECT * FROM certificates WHERE learner_id='student'")).length,0);
 assert.ok((await history('student','practical')).theory_completed_at);
 assert.equal((await m.report.trainingReport(null)).records.find(r=>r.learnerId==='student'&&r.courseId==='practical').status,'in-progress');
 const tiles=await (await call(m.courses,'GET','/api/courses',null,{user:'student'})).json();assert.equal(tiles.courses.find(c=>c.id==='practical').awaitingAssessment,true);
 assert.equal((await call(m.assessor,'GET','/api/assessor',null,{user:'student'})).status,403);
 const queue=await (await call(m.assessor,'GET','/api/assessor',null,{user:'assessor'})).json();assert.equal(queue.pending.length,1);
 const outside=await (await call(m.assessor,'GET','/api/assessor',null,{user:'wrong'})).json();assert.equal(outside.pending.length,0);
 for(const actor of ['wrong','expired','student'])assert.equal((await assessment(actor)).status,400);
 assert.equal((await assessment('assessor',{declaration:false})).status,400);
 assert.equal((await assessment('assessor',{date:'2099-01-01'})).status,400);
 assert.equal((await assessment('assessor',{outcome:'not_yet_competent'})).status,400);
 assert.equal((await assessment('assessor',{outcome:'not_yet_competent',notes:'Repeat lifting technique'})).status,200);
 assert.equal((await q("SELECT * FROM certificates WHERE learner_id='student'")).length,0);
 const creditBefore=(await one('SELECT count(*)::int n FROM credit_ledger')).n;
 assert.equal((await assessment('assessor')).status,200);
 assert.equal((await one('SELECT count(*)::int n FROM credit_ledger')).n,creditBefore);
 assert.equal((await m.report.trainingReport(null)).records.find(r=>r.learnerId==='student'&&r.courseId==='practical').status,'completed');
 const cert=await one("SELECT * FROM certificates WHERE learner_id='student'");assert.equal(cert.assessor_name,'assessor');assert.equal(cert.completed_at,today+'T00:00:00.000Z');
 assert.equal((await assessment('assessor')).status,400);
 await q("UPDATE learners SET name='Changed name' WHERE id='assessor'");assert.equal((await one('SELECT assessor_name FROM certificates WHERE token=$1',cert.token)).assessor_name,'assessor');
 const pass=(await history('student','practical')).passed_assessment_id;
 assert.equal((await call(m.assessor,'POST','/api/assessor',{action:'revoke',id:pass,reason:'Incorrect learner'},{user:'assessor'})).status,403);
 assert.equal((await call(m.assessor,'POST','/api/assessor',{action:'revoke',id:pass,reason:'Incorrect learner'},{admin:true})).status,200);
 await q("SELECT issue_course_certificate('student','practical-pack')");assert.equal((await q("SELECT * FROM certificates WHERE learner_id='student' AND archived_at IS NULL")).length,0);
 assert.equal((await assessment('assessor')).status,200);
 assert.equal((await q('SELECT * FROM practical_assessments WHERE assignment_id=$1',h.id)).length,3);
 assert.equal((await q("SELECT * FROM certificates WHERE learner_id='student'")).length,2);
 assert.equal((await call(m.courses,'GET','/api/courses',null,{user:'external'})).status,403);
 assert.equal((await call(m.assessor,'POST','/api/assessor',{action:'requirement',courseId:'practical',required:false},{user:'assessor'})).status,403);
 assert.equal((await call(m.assessor,'POST','/api/assessor',{action:'requirement',courseId:'practical',required:false},{admin:true,origin:'https://evil.invalid'})).status,403);
 // Self-assessment is rejected even with a valid course grant.
 await assign('self','practical');const self=await history('self','practical');
 await assert.rejects(q('SELECT record_practical_assessment($1,$2,$3,$4,true,$5)',self.id,'self','pass',today,''),/not permitted/);
 console.log('PASS assessor requirements, certificate gating, scoped access, qualification expiry, unsuccessful attempts, declaration, dates, credit preservation, duplicate protection, immutable identity, revocation, reassessment, external-only restrictions and CSRF.');
}finally{await pg.close();rmSync(dir,{recursive:true,force:true});delete globalThis.__creditTest;}
