'use client';
import {useEffect,useState} from 'react';
import {useLanguage} from '@/components/language-provider';
import PageHeader from '@/components/page-header';
import {Input} from '@/components/ui/input';
import {NativeSelect} from '@/components/ui/native-select';
import '@/components/manage-users.css';
import './assessor.css';
type Row={id:string;name:string;email?:string;workday_id?:string|null;course_title:string;store_id:string;country:string;theory_completed_at?:string;assessor_name?:string;outcome?:string;assessed_at?:string;recorded_at?:string;notes?:string;revoked_at?:string;revoke_reason?:string};
type Data={admin:boolean;pending:Row[];history:Row[];courses?:{id:string;title:string;assessor_required:boolean}[];people?:{id:string;name:string;email:string}[];grants?:{id:string;name:string;title:string;qualification:string;site_id:string;expires_on:string|null;active:boolean}[];stores:{id:string;name:string;country:string}[]};
export default function Assessor(){
 const {t,date:formatDate}=useLanguage();
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('pending'),[search,setSearch]=useState(''),[site,setSite]=useState(''),[country,setCountry]=useState(''),[course,setCourse]=useState(''),[selected,setSelected]=useState<Row|null>(null),[external,setExternal]=useState(false);
 async function load(){const r=await fetch('/api/assessor',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);}
 useEffect(()=>{if(selected)document.getElementById('assessment-form')?.scrollIntoView({behavior:'smooth'});},[selected]);
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 async function save(body:object){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/assessor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error);setSelected(null);await load();setNotice('Saved.');return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy(false);}}
 const date=(v?:string|null)=>v?formatDate(v):'—';
 const rows=(tab==='history'?data?.history:data?.pending)||[];
 const visibleRows=rows.filter(r=>(!country||r.country===country)&&(!site||r.store_id===site)&&(!course||r.course_title===course)&&[r.name,r.email,r.workday_id].filter(Boolean).join(' ').toLowerCase().includes(search.trim().toLowerCase()));
 return <div className="shell course-admin app-page assessor-shell"><PageHeader title={t("Assessor")} view="assessor"/><main className="main assessor-page manage-users">{error&&<p role="alert" className="error">{t(error)}</p>}{notice&&<p role="status">{t(notice)}</p>}
 {!data&&!error&&<p>{t("Loading…")}</p>}{data&&<><nav className="user-view-tabs pill-switch assessor-tabs" aria-label={t("Assessor")}>{['pending','history',...(data.admin?['settings']:[])].map(v=><button key={v} aria-pressed={tab===v} onClick={()=>{setTab(v);setSelected(null);setCourse('');}}>{t(v==='pending'?'Awaiting assessment':v==='history'?'Assessment history':'Settings & assessors')}</button>)}</nav>
 {tab!=='settings'&&<section className="paper user-panel assessor-results">
 <div className="directory-toolbar"><Input type="search" aria-label={t('Search learners')} placeholder={t('Name, email or Workday ID')} value={search} onChange={e=>setSearch(e.target.value)}/></div>
 <div className="directory-filters">
 <label>{t('Country')}<NativeSelect value={country} onChange={e=>{setCountry(e.target.value);setSite('');}}><option value="">{t('All countries')}</option>{[...new Set(rows.map(r=>r.country))].sort().map(c=><option key={c} value={c}>{c}</option>)}</NativeSelect></label>
 <label>{t('Store')}<NativeSelect value={site} onChange={e=>setSite(e.target.value)}><option value="">{t('All authorised sites')}</option>{data.stores.filter(s=>!country||s.country===country).map(s=><option key={s.id} value={s.id}>{s.name} · {s.country}</option>)}</NativeSelect></label>
 <label>{t('Course')}<NativeSelect value={course} onChange={e=>setCourse(e.target.value)}><option value="">{t('All courses')}</option>{[...new Set(rows.map(r=>r.course_title))].sort().map(c=><option key={c}>{c}</option>)}</NativeSelect></label>
 </div>
 <p>{t(tab==='pending'?'Only learners who have completed the required online theory appear here.':'All attempts are retained. Practical reassessments do not use course credits.')}</p><div className="assessor-list">{visibleRows.map(r=><article key={r.id}><h2>{r.name}</h2><p>{r.course_title}</p><p>{data.stores.find(s=>s.id===r.store_id)?.name||r.store_id} · {r.country}</p>{tab==='pending'?<><p>{t("Theory completed")}{' '}{date(r.theory_completed_at)}</p><button disabled={busy} onClick={()=>setSelected(r)}>{t("Record assessment")}</button></>:<><strong>{t(r.revoked_at?'Revoked':r.outcome==='pass'?'Passed':'Not yet competent')}</strong><p>{r.assessor_name}{t("· Assessed")}{' '}{date(r.assessed_at)}{t("· Recorded")}{' '}{date(r.recorded_at)}</p><p>{r.notes}</p>{r.revoked_at&&<p>{t("Reason:")}{r.revoke_reason}</p>}{data.admin&&!r.revoked_at&&r.outcome==='pass'&&<button disabled={busy} onClick={()=>{const reason=prompt(t('Reason for revoking this assessment and certificate'));if(reason?.trim())void save({action:'revoke',id:r.id,reason});}}>{t("Revoke sign-off")}</button>}</>}</article>)}</div>{visibleRows.length===0&&<p className="empty">{t("No records to show.")}</p>}</section>}
 {selected&&<section id="assessment-form" className="paper user-panel assessor-panel"><h2>{t("Assess")}{' '}{selected.name}</h2><p>{selected.course_title}</p><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await save({action:'assess',id:selected.id,outcome:f.get('outcome'),date:f.get('date'),notes:f.get('notes'),declaration:f.has('declaration')});}}><label>{t("Outcome")}<select name="outcome"><option value="pass">{t("Pass — competent")}</option><option value="not_yet_competent">{t("Not yet competent")}</option></select></label><label>{t("Practical assessment date")}<input required name="date" type="date" min={selected.theory_completed_at?.slice(0,10)} max={new Date().toISOString().slice(0,10)} defaultValue={new Date().toISOString().slice(0,10)}/></label><label>{t("Notes / evidence reference (reason required if not yet competent)")}<textarea name="notes" maxLength={5000}/></label><label className="assessor-check"><input type="checkbox" name="declaration"/>{t("I confirm that I carried out the practical assessment for this learner and assessed them as competent against the course practical assessment criteria. Required for a pass.")}</label><button disabled={busy}>{t("Save assessment")}</button><button type="button" disabled={busy} onClick={()=>setSelected(null)}>{t("Cancel")}</button></form></section>}
 {tab==='settings'&&<><section className="paper user-panel assessor-panel"><h2>{t("Course requirements")}</h2><p>{t("Applies to this organisation. Changes affect new assignments only; existing requirements and certificates are retained.")}</p>{data.courses?.map(c=><label className="assessor-check" key={c.id}><input type="checkbox" checked={c.assessor_required} disabled={busy} onChange={e=>void save({action:'requirement',courseId:c.id,required:e.target.checked})}/>{c.title}{t("— assessor sign-off required")}</label>)}</section>
 <section className="paper user-panel assessor-panel"><h2>{t("Authorise an assessor")}</h2><form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);if(await save({action:'grant',external,...Object.fromEntries(f)}))form.reset();}}><label className="assessor-check"><input type="checkbox" checked={external} onChange={e=>setExternal(e.target.checked)}/>{t("Create external assessor-only account")}</label>{external?<><label>{t("Name")}<input required name="name" maxLength={101}/></label><label>{t("Email")}<input required type="email" name="email"/></label><label>{t("Initial password")}<input required type="password" name="password" minLength={16} maxLength={128} autoComplete="new-password"/></label><p>{t("Share the login details securely. No invitation email is sent.")}</p></>:<label>{t("Existing user")}<select required name="personId"><option value="">{t("Choose user")}</option>{data.people?.map(p=><option key={p.id} value={p.id}>{p.name} — {p.email}</option>)}</select></label>}<label>{t("Authorised course")}<select required name="courseId"><option value="">{t("Choose course")}</option>{data.courses?.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>{t("Scope")}<select required name="siteId"><option value="*">{t("All sites in this organisation")}</option>{data.stores.map(s=><option key={s.id} value={s.id}>{s.name} · {s.country}</option>)}</select></label><label>{t("Qualification / reference")}<input required name="qualification" maxLength={2000}/></label><label>{t("Qualification expiry (if applicable)")}<input type="date" name="expiresOn" min={new Date().toISOString().slice(0,10)}/></label><button disabled={busy}>{t("Authorise assessor")}</button></form></section>
 <section className="paper user-panel assessor-panel"><h2>{t("Authorisations")}</h2>{data.grants?.map(g=><article key={g.id}><strong>{g.name} · {g.title}</strong><p>{g.site_id==='*'?t('All sites in this organisation'):data.stores.find(s=>s.id===g.site_id)?.name||g.site_id} · {g.qualification}{t("· Expires:")}{' '}{date(g.expires_on)} · {t(!g.active?'Disabled':g.expires_on&&g.expires_on.slice(0,10)<new Date().toISOString().slice(0,10)?'Expired':'Active')}</p>{g.active&&<button disabled={busy} onClick={()=>void save({action:'disable',id:g.id})}>{t("Disable authorisation")}</button>}</article>)}</section></>}
 </>}</main></div>;
}
