'use client';
import {useEffect,useState} from 'react';
import PageHeader from '@/components/page-header';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {useLanguage} from '@/components/language-provider';
import './recognition.css';
type Decision={id:string;kind:string;reason:string;evidence_ref:string;qualification:string|null;achieved_on:string|null;valid_until:string;approved_by:string;approved_at:string;revoked_at:string|null;revocation_reason:string|null};
type Row={id:string;name:string;email:string;workday_id:string|null;title:string;assessor_required:boolean;completed_at:string|null;due_at:string|null;decisions:Decision[]|null};
export default function Recognition(){
 const {t,date}=useLanguage();const [search,setSearch]=useState(''),[page,setPage]=useState(1),[refresh,setRefresh]=useState(0),[data,setData]=useState<{enabled:boolean;rows:Row[];hasMore:boolean}|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<{row:Row;decision?:Decision}|null>(null),[kind,setKind]=useState('exempt');
 useEffect(()=>{const ctrl=new AbortController();setData(null);const timer=setTimeout(()=>fetch('/api/training-recognition?'+new URLSearchParams({search,page:String(page)}),{signal:ctrl.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);return d;}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message);}),200);return()=>{ctrl.abort();clearTimeout(timer);};},[search,page,refresh]);
 async function save(form:HTMLFormElement){if(!selected)return;setBusy(true);setError('');try{const values=Object.fromEntries(new FormData(form));const r=await fetch('/api/training-recognition',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values,kind,validUntil:values.validUntil?new Date(String(values.validUntil)+'T23:59:59.999Z').toISOString():undefined,assignmentId:selected.row.id,action:selected.decision?'revoke':'approve',id:selected.decision?.id})});const d=await r.json();if(!r.ok)throw new Error(d.error);setSelected(null);setRefresh(v=>v+1);setNotice('Training decision saved.');}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}
 const label=(kind:string)=>kind==='exempt'?'Exempt':kind==='recognised'?'Prior learning recognised':'Deadline extended';
 return <div className="shell course-admin"><PageHeader view="settings" title={t('Training exemptions and prior learning')}/><main className="main recognition-page">
 <p><a href="/admin/settings/">{t('Settings')}</a></p><p>{t('A reason, evidence reference and expiry date are required.')}</p>
 <p>{t('Exemptions are excluded from compliance. Prior learning counts as compliant. Certificates and pathways still require course completion.')}</p>
 {data&&!data.enabled&&<p role="status">{t('Feature off. Existing decisions remain valid and can be revoked.')}</p>}
 <Input type="search" aria-label={t('Search learners and courses')} placeholder={t('Search learners and courses')} value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/>
 {notice&&<p role="status">{t(notice)}</p>}{error&&!selected&&<p className="error" role="alert">{t(error)}</p>}
 {!data?<p>{t('Loading training records…')}</p>:<><div className="recognition-list">{data.rows.map(row=>{const current=row.decisions?.find(d=>!d.revoked_at);return <section className="paper recognition-row" key={row.id}><div><h2>{row.name}</h2><p>{row.email} {row.workday_id&&' · '+row.workday_id}</p><h3>{row.title}</h3>{row.due_at&&<p>{t('Due')} {date(row.due_at)}</p>}{row.assessor_required&&<p>{t('Practical assessor sign-off required before certification')}</p>}</div><div>{row.decisions?.map(d=><details key={d.id}><summary>{t(label(d.kind))} · {t(d.revoked_at?'Revoked':Date.parse(d.valid_until)<=Date.now()?'Expired':'Active')} · {date(d.valid_until)}</summary><p>{d.reason}</p><p>{t('Evidence reference')}: {d.evidence_ref}</p>{d.qualification&&<p>{d.qualification} · {date(d.achieved_on!)}</p>}<p>{t('Approved by')}: {d.approved_by} · {date(d.approved_at)}</p>{d.revoked_at&&<p>{t('Revoked')} {date(d.revoked_at)}: {d.revocation_reason}</p>}</details>)}
 {current?<Button variant="outline" onClick={()=>{setError('');setSelected({row,decision:current});}}>{t('Revoke decision')}</Button>:data.enabled&&!row.completed_at?<Button variant="outline" onClick={()=>{setKind(row.assessor_required?'extension':'exempt');setError('');setSelected({row});}}>{t('Record decision')}</Button>:null}</div></section>;})}</div>{!data.rows.length&&<p>{t('No assignments match this view.')}</p>}<div className="recognition-pagination"><Button variant="outline" disabled={page===1} onClick={()=>setPage(p=>p-1)}>{t('Previous')}</Button><span>{page}</span><Button variant="outline" disabled={!data.hasMore} onClick={()=>setPage(p=>p+1)}>{t('Next')}</Button></div></>}
 <Dialog open={!!selected} onOpenChange={v=>{if(!v&&!busy)setSelected(null);}}><DialogContent><DialogHeader><DialogTitle>{t(selected?.decision?'Revoke decision':'Record decision')}</DialogTitle><DialogDescription>{selected?.row.name} · {selected?.row.title}</DialogDescription></DialogHeader><form className="recognition-form" onSubmit={e=>{e.preventDefault();void save(e.currentTarget);}}>
 {!selected?.decision&&<><label>{t('Decision')}<select value={kind} onChange={e=>setKind(e.target.value)}>{!selected?.row.assessor_required&&<><option value="exempt">{t('Temporary exemption')}</option><option value="recognised">{t('Recognised prior learning')}</option></>}<option value="extension">{t('Deadline extension')}</option></select></label>{kind==='recognised'&&<><label>{t('Qualification or external training')}<Input name="qualification" required maxLength={300}/></label><label>{t('Award date')}<Input name="achievedOn" type="date" required max={new Date().toISOString().slice(0,10)}/></label></>}
 <label>{t(kind==='extension'?'New deadline':'Valid until')}<Input name="validUntil" type="date" required min={new Date().toISOString().slice(0,10)}/></label><label>{t('Evidence reference')}<Input name="evidenceRef" required minLength={3} maxLength={2000} placeholder={t('Certificate reference or secure document location')}/></label></>}
 <label>{t('Reason')}<textarea name="reason" required minLength={3} maxLength={2000}/></label>{error&&<p role="alert" className="error">{t(error)}</p>}<div className="editor-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>setSelected(null)}>{t('Cancel')}</Button><Button disabled={busy}>{t(busy?'Saving…':'Save decision')}</Button></div></form></DialogContent></Dialog>
 </main></div>;
}
