'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {useLanguage} from '@/components/language-provider';
import type {CreditAccount} from '@/lib/credits';
import './period-report.css';
type Row={id:string;learnerName:string;courseTitle:string;assignedAt:string;startedAt:string|null;completedAt:string|null;cancelledAt:string|null;cancelledBy:string|null;reason:string|null;refunded:boolean;hasPrevious:boolean;billed:boolean;canRemove:boolean;canRenew:boolean};
export default function AssignmentHistory({storeId,learnerId,refresh,onChange}:{storeId:string;learnerId:string;refresh:number;onChange:(notice:string)=>void}){
 const {t,date}=useLanguage();const [data,setData]=useState<{rows:Row[];hasMore:boolean;credits:CreditAccount|null}|null>(null),[view,setView]=useState('current'),[page,setPage]=useState(1),[search,setSearch]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[selected,setSelected]=useState<{row:Row;action:'remove'|'renew'}|null>(null),[reason,setReason]=useState('');
 useEffect(()=>setPage(1),[storeId,learnerId,view,search]);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setData(null);setError('');const timer=setTimeout(()=>{fetch('/api/store/assignments?'+new URLSearchParams({storeId,learnerId,view,page:String(page),search}),{cache:'no-store',signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);return d;}).then(d=>{if(!controller.signal.aborted){setData(d);setLoading(false);}}).catch(e=>{if(e.name!=='AbortError'){setError(e.message);setLoading(false);}});},200);return()=>{clearTimeout(timer);controller.abort();};},[storeId,learnerId,view,page,search,refresh]);
 async function submit(){if(!selected)return;setBusy(true);setError('');try{const r=await fetch('/api/store/assignments?'+new URLSearchParams({storeId}),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({assignmentId:selected.row.id,action:selected.action,reason})});const d=await r.json();if(!r.ok)throw new Error(d.error);setSelected(null);setReason('');onChange(selected.action==='renew'?'Assigned':d.refunded?'Credit returned':'No credit returned');}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}
 const credits=data?.credits;
 return <section className="paper assignment-history"><div className="assignment-history-head"><h2>{t('Assignments')}</h2>{credits&&<div className={'credit-balance'+(credits.balance<10?' low':'')}><strong>{credits.balance}</strong> {t('Credits available')}<small>{t('Used this period')}: {credits.usedThisPeriod} · {t('Next top-up')}: {credits.nextTopup?date(credits.nextTopup):t('Calendar required')}</small></div>}</div>
 <div className="assignment-history-filters"><div className="assignment-view-scroll"><div className="assignment-view-tabs pill-switch" role="group" aria-label={t('Assignments')}><button className={view==='current'?'selected':''} aria-pressed={view==='current'} onClick={()=>setView('current')}>{t('Current assignments')}</button><button className={view==='removed'?'selected':''} aria-pressed={view==='removed'} onClick={()=>setView('removed')}>{t('Removed assignments')}</button></div></div><Input type="search" aria-label={t('Search assignments')} placeholder={t('Search assignments')} value={search} onChange={e=>setSearch(e.target.value)}/></div>
 {error&&!selected&&<p className="error" role="alert">{t(error)}</p>}{loading&&<p role="status">{t('Loading training records…')}</p>}
 {data&&<><div className="table-scroll"><table><thead><tr>{['Employee','Course','Assigned','Status','Actions'].map(k=><th scope="col" key={k}>{t(k)}</th>)}</tr></thead><tbody>{data.rows.map(row=><tr key={row.id}><th scope="row">{row.learnerName}</th><td>{row.courseTitle}</td><td>{date(row.assignedAt)}</td><td>{t(row.cancelledAt?'Removed':row.completedAt?'Completed':row.startedAt?'In progress':'Not started')}{row.cancelledAt&&<small>{date(row.cancelledAt)} · {row.cancelledBy}<br/>{row.reason}<br/>{t(row.refunded?'Credit returned':'No credit returned')}</small>}</td><td>{!row.cancelledAt&&<Button variant="outline" disabled={busy||!row.canRemove} onClick={()=>{setError('');setReason('');setSelected({row,action:'remove'});}}>{t('Remove assignment')}</Button>}{row.canRenew&&<Button variant="outline" disabled={busy} onClick={()=>{setError('');setSelected({row,action:'renew'});}}>{t('Renew course')}</Button>}</td></tr>)}</tbody></table>{!data.rows.length&&<p>{t('No assignments match this view.')}</p>}</div><div className="assignment-pagination"><Button variant="outline" disabled={page===1||loading||busy} onClick={()=>setPage(v=>v-1)}>{t('Previous')}</Button><span>{page}</span><Button variant="outline" disabled={!data.hasMore||loading||busy} onClick={()=>setPage(v=>v+1)}>{t('Next')}</Button></div></>}
 <Dialog open={!!selected} onOpenChange={open=>{if(!open&&!busy)setSelected(null);}}><DialogContent><DialogHeader><DialogTitle>{t(selected?.action==='renew'?'Renew course':'Remove assignment')}</DialogTitle><DialogDescription>{selected?.row.learnerName} · {selected?.row.courseTitle}</DialogDescription></DialogHeader>{selected&&<form onSubmit={e=>{e.preventDefault();void submit();}}><p>{t(selected.action==='renew'?'A new assignment will use one credit. Previous training evidence is retained.':!selected.row.billed?'This assignment predates credit billing. No credit or charge is changed.':'One credit will be returned and the charge reversed.')}</p>{selected.action==='remove'&&<>{selected.row.hasPrevious&&<p>{t('The previous assignment will be restored with its original certificate expiry.')}</p>}<label>{t('Reason')}<Input required minLength={3} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label></>}{error&&<p className="error" role="alert">{t(error)}</p>}<div className="editor-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>setSelected(null)}>{t('Cancel')}</Button><Button type="submit" disabled={busy}>{t(busy?'Saving…':selected.action==='renew'?'Renew course':'Remove assignment')}</Button></div></form>}</DialogContent></Dialog>
 </section>;
}
