"use client";
import {useLanguage} from '@/components/language-provider';
import {useEffect,useState} from 'react';
import {Input} from '@/components/ui/input';
import {NativeSelect} from '@/components/ui/native-select';
import {Button} from '@/components/ui/button';
import '@/components/manage-users.css';
type Event={id:string;recorded_at:string;actor:string;entity:string;action:string;reason:string|null;previous_state:Record<string,unknown>|null;next_state:Record<string,unknown>|null};
const label=(v:string)=>v.replaceAll('_',' ');
export default function AuditTrail(){const {t}=useLanguage();
 const [search,setSearch]=useState(''),[entity,setEntity]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[page,setPage]=useState(1),[rows,setRows]=useState<Event[]>([]),[total,setTotal]=useState(0),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');const timer=setTimeout(()=>{fetch('/api/audit?'+new URLSearchParams({search,entity,from,to,page:String(page)}),{signal:controller.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);return d;}).then(d=>{setRows(d.events);setTotal(d.total);setLoading(false);}).catch(e=>{if(e.name!=='AbortError'){setError(e.message);setLoading(false);}});},200);return()=>{controller.abort();clearTimeout(timer);};},[search,entity,from,to,page]);
 return <section className="paper user-panel"><p>{t("Read-only history of account, access, course, assignment, certificate and assessment changes. Times are shown in your local timezone.")}</p>
 <div className="directory-toolbar"><Input type="search" placeholder={t("Search person, course, administrator or reason")} aria-label={t("Search audit trail")} value={search} onChange={e=>{setSearch(e.target.value);setPage(1);}}/></div>
 <div className="directory-filters"><label>{t("Record type")}<NativeSelect value={entity} onChange={e=>{setEntity(e.target.value);setPage(1);}}><option value="">{t("All records")}</option>{['learners','courses','course_versions','assignment_history','certificates','practical_assessments','assessor_grants','reporting_access','platform_admins','store_managers','learning_pathways','pathway_enrolments','email'].map(v=><option key={v} value={v}>{v==='email'?t('Email notifications'):label(v)}</option>)}</NativeSelect></label><label>{t("From")}<Input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1);}}/></label><label>{t("To")}<Input type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1);}}/></label></div>
 {error&&<p role="alert" className="error">{t(error)}</p>}{loading?<p role="status">{t("Loading history…")}</p>:<>{rows.map(row=><details key={row.id} className="employee-card" style={{display:'block'}}><summary><strong>{label(row.entity)} · {row.action}</strong> · {String(row.next_state?.name||row.next_state?.title||row.next_state?.course_title||row.previous_state?.name||'')}<br/><small>{new Date(row.recorded_at).toLocaleString()} · {row.actor}</small></summary>{row.reason&&<p>{row.reason}</p>}<div className="table-scroll"><table><thead><tr><th>{t("Field")}</th><th>{t("Before")}</th><th>{t("After")}</th></tr></thead><tbody>{[...new Set([...Object.keys(row.previous_state||{}),...Object.keys(row.next_state||{})])].filter(k=>JSON.stringify(row.previous_state?.[k])!==JSON.stringify(row.next_state?.[k])).map(k=><tr key={k}><td>{label(k)}</td><td>{String(row.previous_state?.[k]??'—')}</td><td>{String(row.next_state?.[k]??'—')}</td></tr>)}</tbody></table></div></details>)}{!rows.length&&<p>{t("No changes match these filters.")}</p>}</>}
 <div className="directory-pagination"><span>{total} {t("events")}</span><Button variant="outline" disabled={loading||page===1} onClick={()=>setPage(page-1)}>{t("Previous")}</Button><span>{page} / {Math.max(1,Math.ceil(total/25))}</span><Button variant="outline" disabled={loading||page*25>=total} onClick={()=>setPage(page+1)}>{t("Next")}</Button></div></section>;
}
