'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { Button } from '@/components/ui/button';
import { NativeSelect } from '@/components/ui/native-select';
import type { Sco } from '@/lib/course-types';
type Launch={token:string;title:string;scos:Sco[];scoId:string;url:string;preview:boolean};
export default function Player({courseId,preview}:{courseId:string;preview:boolean}){
 const [launch,setLaunch]=useState<Launch|null>(null),[error,setError]=useState(''),[saving,setSaving]=useState(''),[busy,setBusy]=useState(true);
 const frame=useRef<HTMLIFrameElement>(null),active=useRef<Launch|null>(null),queue=useRef<Promise<void>>(Promise.resolve()),sequence=useRef(0),failed=useRef(false),latest=useRef<Record<string,string>|null>(null);
 const send=useCallback((data:Record<string,string>)=>{latest.current=data;const current=active.current;if(!current)return;const seq=++sequence.current;setSaving(current.preview?'Preview · progress not recorded':'Saving…');queue.current=queue.current.then(async()=>{const r=await fetch('/api/scorm',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'save',token:current.token,sequence:seq,data}),keepalive:true});const d:any=await r.json();if(!r.ok)throw new Error(d.error);failed.current=false;setError('');setSaving(current.preview?'Preview · progress not recorded':'Progress saved');}).catch(e=>{failed.current=true;setError(e.message||'Progress could not be saved. Keep this page open and retry.');setSaving('Progress not saved');});},[]);
 const start=useCallback(async(scoId?:string)=>{setBusy(true);setError('');try{const r=await fetch('/api/scorm',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'launch',courseId,scoId,preview})});const d:any=await r.json();if(!r.ok)throw new Error(d.error);active.current=d;sequence.current=0;latest.current=null;failed.current=false;setLaunch(d);setSaving(preview?'Preview · progress not recorded':'Progress saves as you learn');}catch(e){setError((e as Error).message);}finally{setBusy(false);}},[courseId,preview]);
 useEffect(()=>{void start();},[start]);
 useEffect(()=>{const receive=(e:MessageEvent)=>{if(e.source!==frame.current?.contentWindow||e.data?.type!=='primark-scorm-save'||e.data.token!==active.current?.token)return;send(e.data.data);};window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive);},[send]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(failed.current||saving==='Saving…'){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[saving]);
 async function flush(){frame.current?.contentWindow?.postMessage({type:'primark-scorm-flush',token:active.current?.token},'*');await new Promise(resolve=>setTimeout(resolve,250));await queue.current;return !failed.current;}
 async function exit(){setBusy(true);if(await flush())location.assign(preview?'/admin/courses/':'/?courses=1');else setBusy(false);}
 return <div className="scorm-player"><header className="topbar"><a className="brand" href={preview?'/admin/courses/':'/?courses=1'} onClick={e=>{e.preventDefault();void exit();}}><strong>PRIMARK</strong><span>Safety Passport</span></a><Button variant="outline" disabled={busy} onClick={exit}>{preview?'Back to courses':'Save & exit'}</Button></header><div className="player-toolbar"><div><h1>{launch?.title||'Opening course…'}</h1><p role="status">{saving}</p></div>{launch&&launch.scos.length>1&&<label>Lesson<NativeSelect value={launch.scoId} disabled={busy} onChange={async e=>{const id=e.target.value;setBusy(true);if(await flush())await start(id);else setBusy(false);}}>{launch.scos.map((s,i)=><option value={s.id} key={s.id}>{i+1}. {s.title}</option>)}</NativeSelect></label>}</div>{error&&<div role="alert" className="error">{error}<div>{latest.current?<Button onClick={()=>send(latest.current!)}>Retry save</Button>:<a href={preview?'/admin/courses/':'/'}>Return to sign in</a>}</div></div>}{busy&&<p className="player-loading">Loading…</p>}{launch&&<iframe key={launch.token} ref={frame} title={launch.title} src={launch.url} sandbox="allow-scripts allow-same-origin allow-forms allow-popups allow-downloads" allow="fullscreen; autoplay" referrerPolicy="no-referrer"/>}</div>;
}
