import type { Language } from './i18n';
const keys=['Register','Login','Registration code','Create password','Password','At least 8 characters.','Already have a pass code?','Existing pass code','Create your password','Save password & login','Back to Login','Please wait…','Your safety training, ready when you are.'];
const words:Record<Exclude<Language,'en'>,string[]>={
  es:['Registrarse','Iniciar sesión','Código de registro','Crear contraseña','Contraseña','Al menos 8 caracteres.','¿Ya tienes un código de acceso?','Código de acceso actual','Crea tu contraseña','Guardar contraseña e iniciar sesión','Volver al inicio de sesión','Espera…','Tu formación en seguridad, cuando tú quieras.'],
  fr:['S’inscrire','Se connecter','Code d’inscription','Créer un mot de passe','Mot de passe','Au moins 8 caractères.','Vous avez déjà un code d’accès ?','Code d’accès actuel','Créez votre mot de passe','Enregistrer et se connecter','Retour à la connexion','Veuillez patienter…','Votre formation à la sécurité, quand vous êtes prêt.'],
  de:['Registrieren','Anmelden','Registrierungscode','Passwort erstellen','Passwort','Mindestens 8 Zeichen.','Bereits einen Zugangscode?','Bisheriger Zugangscode','Erstelle dein Passwort','Passwort speichern und anmelden','Zurück zur Anmeldung','Bitte warten…','Deine Sicherheitsschulung – bereit, wenn du es bist.'],
  it:['Registrati','Accedi','Codice di registrazione','Crea password','Password','Almeno 8 caratteri.','Hai già un codice di accesso?','Codice di accesso attuale','Crea la tua password','Salva password e accedi','Torna al login','Attendi…','La tua formazione sulla sicurezza, quando vuoi.'],
  nl:['Registreren','Inloggen','Registratiecode','Wachtwoord aanmaken','Wachtwoord','Minimaal 8 tekens.','Heb je al een toegangscode?','Bestaande toegangscode','Maak je wachtwoord aan','Wachtwoord opslaan en inloggen','Terug naar inloggen','Even geduld…','Je veiligheidstraining, wanneer jij er klaar voor bent.'],
  pt:['Registar','Iniciar sessão','Código de registo','Criar palavra-passe','Palavra-passe','Pelo menos 8 caracteres.','Já tens um código de acesso?','Código de acesso atual','Cria a tua palavra-passe','Guardar e iniciar sessão','Voltar ao início de sessão','Aguarda…','A tua formação em segurança, quando quiseres.'],
  pl:['Zarejestruj się','Zaloguj się','Kod rejestracyjny','Utwórz hasło','Hasło','Co najmniej 8 znaków.','Masz już kod dostępu?','Dotychczasowy kod dostępu','Utwórz swoje hasło','Zapisz hasło i zaloguj się','Wróć do logowania','Proszę czekać…','Twoje szkolenie z bezpieczeństwa, gdy będziesz gotowy.'],
  ro:['Înregistrare','Autentificare','Cod de înregistrare','Creează parola','Parolă','Cel puțin 8 caractere.','Ai deja un cod de acces?','Codul de acces existent','Creează-ți parola','Salvează parola și autentifică-te','Înapoi la autentificare','Te rugăm să aștepți…','Instruirea ta de siguranță, când ești pregătit.'],
  cs:['Zaregistrovat se','Přihlásit se','Registrační kód','Vytvořit heslo','Heslo','Alespoň 8 znaků.','Máte už přístupový kód?','Stávající přístupový kód','Vytvořte si heslo','Uložit heslo a přihlásit se','Zpět na přihlášení','Čekejte prosím…','Vaše bezpečnostní školení, až budete připraveni.'],
  sk:['Zaregistrovať sa','Prihlásiť sa','Registračný kód','Vytvoriť heslo','Heslo','Aspoň 8 znakov.','Máte už prístupový kód?','Existujúci prístupový kód','Vytvorte si heslo','Uložiť heslo a prihlásiť sa','Späť na prihlásenie','Čakajte prosím…','Vaše bezpečnostné školenie, keď budete pripravení.'],
  sl:['Registracija','Prijava','Registracijska koda','Ustvari geslo','Geslo','Najmanj 8 znakov.','Že imate kodo za dostop?','Obstoječa koda za dostop','Ustvarite svoje geslo','Shrani geslo in se prijavi','Nazaj na prijavo','Prosimo, počakajte…','Vaše varnostno usposabljanje, ko ste pripravljeni.'],
  hu:['Regisztráció','Bejelentkezés','Regisztrációs kód','Jelszó létrehozása','Jelszó','Legalább 8 karakter.','Van már belépési kódod?','Meglévő belépési kód','Hozd létre a jelszavad','Jelszó mentése és bejelentkezés','Vissza a bejelentkezéshez','Kérjük, várj…','Biztonsági képzésed, amikor készen állsz.'],
  ar:['التسجيل','تسجيل الدخول','رمز التسجيل','إنشاء كلمة مرور','كلمة المرور','8 أحرف على الأقل.','هل لديك رمز دخول بالفعل؟','رمز الدخول الحالي','أنشئ كلمة المرور','حفظ كلمة المرور وتسجيل الدخول','العودة إلى تسجيل الدخول','يرجى الانتظار…','تدريبك على السلامة، عندما تكون مستعدًا.'],
};
export const authCopy=Object.fromEntries(Object.entries(words).map(([lang,values])=>[lang,Object.fromEntries(keys.map((key,i)=>[key,values[i]]))])) as Record<Exclude<Language,'en'>,Record<string,string>>;
