export type ShotKind = "photo" | "optional" | "reuse" | "screen";
export type ShotSlide = { number: number; title: string; subject: string; details: string[]; kind: ShotKind };
export type ShotModule = { number: number; title: string; location: string; slides: ShotSlide[] };
const slide = (number: number, title: string, subject: string, details: string[], kind: ShotKind = "photo"): ShotSlide => ({ number, title, subject, details, kind });

export const shotModules: ShotModule[] = [
  { number: 1, title: "Welcome and Your Part in Safety", location: "Shop floor · Staff area", slides: [
    slide(1, "Cover", "Welcoming Primark colleague on the shop floor", ["Use a recognisable store background and current branding.", "Position the colleague towards the right. Leave uncluttered space on the left for the title.", "This is an optional replacement for the existing cover."], "optional"),
    slide(2, "Why this matters", "Typical shop-floor working environment", ["Show a colleague replenishing stock, with displays, a clear customer route and normal store equipment visible.", "Capture the real environment a new starter will enter. Take a wide view and a closer working shot."]),
    slide(3, "Safety is shared", "Manager showing a colleague how to work safely", ["Capture a natural briefing beside a real task, such as preparing a stock trolley or checking a work area.", "Show the two colleagues interacting rather than both looking at the camera."]),
    slide(4, "Report it immediately", "Colleague reporting a concern to a supervisor", ["Show them discussing an identifiable item or location.", "Also photograph a blank Accident Book and an approved demonstration of the reporting system, if current and available.", "Keep personal information and real incident records out of shot."]),
    slide(5, "First aid and support", "First-aid information, first-aid box and Safety Committee information", ["Take separate readable close-ups of the first-aider notice, first-aid box and Safety Committee information.", "Take a wider shot showing where staff find these items. Include a first aider if available.", "Ask the store lead to check that displayed information is current and suitable for use in training."]),
    slide(6, "Remember", "Reuse the strongest reporting or safety-briefing photograph", ["Use a photograph from slide 3 or 4. A different angle gives the editor another option.", "No additional photography is required for this slide."], "reuse"),
  ]},
  { number: 2, title: "Safe on the Shop Floor", location: "Shop floor · Escalators · Lift · Stairs", slides: [
    slide(1, "Cover", "Colleague with escalators in the background", ["Keep the store recognisable without a busy crowd.", "Position the colleague towards the right and leave space on the left for the title."], "optional"),
    slide(2, "Escalator hazards", "Escalator overview and close-ups of the hazard areas", ["Capture the step-to-side gap, the point where the steps enter the landing, and the handrail entry point.", "Include existing warning signs and a wider view of the escalator.", "Photograph from a safe position. Keep hands, clothing and props away from moving parts."]),
    slide(3, "Keeping customers safe", "Lift entrance, lift-direction signage and clear escalator landing", ["Take separate photographs of the lift entrance, directional signs and clear landing.", "If practical, show a colleague directing an adult with an empty pushchair towards the lift. No child is needed."]),
    slide(4, "Escalator emergency", "Actual escalator emergency-stop buttons", ["Photograph the stop-button locations at both the top and bottom landings.", "At each location, take a close-up of the button and label, then a wider shot showing where it sits.", "Do not press the stop button for the photograph."]),
    slide(5, "Stairs, slips and trips", "Using a stair handrail, removing dropped stock and responding to a spill", ["Show a colleague using the stairs with one hand on the handrail.", "In a controlled area, photograph a colleague collecting a hanger or dropped item.", "Make a dry demonstration with the store's actual warning sign and cleaning equipment. Do not create a live slip hazard."]),
    slide(6, "Footwear", "Store-approved footwear being worn", ["Ask the store lead to select a representative pair that meets current requirements.", "Take a side view showing the closed toe and heel, plus a separate close-up of the sole."]),
    slide(7, "Remember", "Reuse handrail, clear-floor and lift photographs", ["Select photographs from slides 3 and 5, with footwear from slide 6 if useful.", "No additional photography is required."], "reuse"),
  ]},
  { number: 3, title: "Safe in the Stockroom", location: "Stockroom · Chemical store", slides: [
    slide(1, "Cover", "Colleague in the actual Primark stockroom", ["Show recognisable stockroom fittings and an orderly, clear aisle.", "Position the colleague towards the right with space on the left for the title."], "optional"),
    slide(2, "The safety knife", "Approved Primark safety knife, safe use and sharps bin", ["Have the store confirm the current approved knife model.", "Take a clean close-up showing the enclosed blade and handle.", "Photograph a colleague cutting packaging using the approved method.", "Take a separate photograph of the labelled sharps bin used for damaged knives."]),
    slide(3, "Ladders and kickstools", "Approved ladder and kickstool, with inspection and use", ["Photograph the actual ladder and kickstool separately.", "Capture a colleague checking the ladder before use.", "Photograph the whole person using it so feet, hands and contact points are visible. Have the safety lead check the demonstration."]),
    slide(4, "Stacking", "Stockroom red line with correctly stacked stock below it", ["Frame the red line and top of the stack together. Capture any local stacking-limit signage.", "Take additional views showing clearance around sprinkler heads.", "Show clear access to exits, fire equipment and electrical equipment. Ask the store lead to confirm the examples."]),
    slide(5, "Conveyors", "Conveyor, emergency stop and both operator positions", ["Photograph the complete arrangement and a readable close-up of the emergency stop.", "Capture the working positions at both ends.", "If practical, show colleagues demonstrating the warning/all-clear communication without operating equipment for the shot.", "If this store has no conveyor, record it as unavailable so an approved image can be sourced elsewhere."]),
    slide(6, "Chemicals", "Designated chemical storage, labels and required protection", ["Show the locked storage area and its signage.", "With the responsible colleague, photograph a representative product label and the protection specified for that product.", "Capture spill-response materials if provided locally. Do not stage a chemical spill."]),
    slide(7, "Remember", "Reuse knife, red-line and reporting photographs", ["Choose particularly clear knife and red-line images from slides 2 and 4.", "No additional photography is required."], "reuse"),
  ]},
  { number: 4, title: "Fire Safety", location: "Fire routes · Sign-in point · Assembly point", slides: [
    slide(1, "Cover", "Colleague or fire warden beside a clear exit route", ["Include an exit sign or fire point in the background and keep access clear.", "Position the person towards the right with space on the left for the title."], "optional"),
    slide(2, "Your first-day walk-round", "Exit route, door-opening mechanism, call point and fire point", ["Take a wider location shot and a close-up of each item.", "Also photograph a manager showing a new colleague the route, if practical.", "Have the fire lead identify the correct route and equipment."]),
    slide(3, "Fire doors", "Closed fire door, signage and exit-door hardware", ["Show the whole fire door, its closer and the clear surrounding area.", "Photograph relevant exit-door opening hardware separately.", "Ask the fire lead to identify the right examples. Do not prop a door open for the photograph."]),
    slide(4, "If you discover a fire", "Actual fire-alarm call point and the route away from it", ["Take a readable close-up and a wider location shot.", "Optionally show a colleague indicating the call point without activating it.", "No simulated fire is needed."]),
    slide(5, "Extinguishers", "Store fire point with installed extinguishers", ["Show normal mounted positions, identification signs and clear access.", "Capture readable labels separately.", "Keep equipment in place. This slide is about recognition and the restriction to trained users."]),
    slide(6, "Evacuation", "Fire warden, evacuation route and actual assembly point", ["Photograph the warden wearing the identification used locally.", "Capture the clear route to the exit and the assembly-point sign with enough background to identify the location.", "An approved, small arranged group can illustrate departmental assembly."]),
    slide(7, "Helping others", "Store assistance arrangements and visitor/contractor sign-in point", ["Ask the fire lead which features colleagues need to recognise, such as a refuge or communication point if it is present and part of the plan.", "Photograph the actual visitor/contractor sign-in location with a blank or demonstration record.", "Do not include personal evacuation information or real visitor details."]),
    slide(8, "Remember", "Reuse call-point, exit and fire-warden photographs", ["Keep the three subjects visually distinct.", "No additional photography is required."], "reuse"),
  ]},
  { number: 5, title: "Manual Handling", location: "Stockroom · Stock movement routes", slides: [
    slide(1, "Cover", "Colleague with an actual Primark trolley or roll cage", ["Show a manageable load and a clear route.", "Position the colleague towards the right with space on the left for the title."], "optional"),
    slide(2, "Why it matters", "Representative everyday stock-handling task", ["Show a colleague moving a normal, light stock box between sensible working positions.", "Capture the working environment and full body. There is no need to stage an injury or poor technique."]),
    slide(3, "Before you lift", "Colleague assessing a load, with a handling aid available", ["Show the box, available trolley or cage, clear route and destination.", "Take a second photograph of the colleague seeking help from another team member."]),
    slide(4, "Safe lifting principles", "A sequence of the same colleague handling the same light box", ["Capture preparation, grip, lifting, carrying close to the body, turning and setting down.", "Use front/three-quarter and side views so feet, hands and body position remain visible.", "Have the store's trained manual-handling lead direct the demonstration."]),
    slide(5, "Height and team lifts", "Approved access platform and a separate team-lift demonstration", ["Show the access equipment actually used for the task and the working height.", "For the team lift, capture both colleagues, their grips, the load and the clear destination.", "Use a light prop and a supervised demonstration."]),
    slide(6, "Rails, cages and trolleys", "Actual garment rail, roll cage and trolley in use", ["Photograph each separately, showing hands, direction of travel, load height and the colleague's view ahead.", "Also capture the pallet truck mentioned in the notes if it is used here, and the local out-of-use label.", "Have the lead confirm each demonstration and use light loads."]),
    slide(7, "Remember", "Reuse load-assessment, lifting and trolley photographs", ["Choose images where the intended action is immediately obvious.", "No additional photography is required."], "reuse"),
  ]},
  { number: 6, title: "Environment and Energy", location: "Waste area · Staff area · EHS notice board", slides: [
    slide(1, "Cover", "Colleague beside the actual store recycling area", ["Include current environmental signage if available.", "Position the colleague towards the right with space on the left for the title."], "optional"),
    slide(2, "Waste", "Waste-separation containers, labels and box reuse", ["Take an overview of the collection point and readable close-ups of each waste-stream label.", "Show a colleague putting an appropriate item in the correct container.", "Photograph an incoming box being reused for outgoing goods."]),
    slide(3, "Energy and water", "Approved everyday energy-saving and water-saving actions", ["Ask the store lead to select ordinary light/equipment controls that staff are authorised to switch off.", "Photograph a colleague demonstrating an appropriate action and a staff-area tap.", "Add context photographs of lighting or other energy-using equipment. Do not switch off operational or safety systems for the shoot."]),
    slide(4, "Our Energy Policy", "Current Energy Policy on the EHS notice board", ["Take a wide shot showing where colleagues find it and a square-on close-up readable at full resolution.", "Capture current energy contact or ideas information.", "Ask for the original policy PDF as well; it will reproduce more clearly than a photograph. Send that separately to the project lead."]),
    slide(5, "Key rules recap", "Reuse photographs from across all six modules", ["Select reporting, clear floors, knife, red line, fire door/exit, handling equipment and recycling images.", "No additional photography is required."], "reuse"),
    slide(6, "Your exam", "Clean screenshots of the final exam and certificate", ["No store photograph is required.", "The project team will supply screenshots with demonstration details when final assessment screens are available.", "An optional colleague-at-device photograph can provide context."], "screen"),
    slide(7, "You're ready", "Manager welcoming a new colleague", ["Capture a natural welcome on the shop floor, if another photograph is needed.", "If showing a certificate, use an approved demonstration copy.", "Alternatively reuse a different frame from the Module 1 welcome shoot."], "optional"),
  ]},
];

export const shotKey = (module: number, slide: number) => `${module}-${slide}`;
export const getShot = (module: number, number: number) => shotModules.find(m => m.number === module)?.slides.find(s => s.number === number);
export const requiredShots = shotModules.flatMap(m => m.slides.filter(s => s.kind === "photo").map(s => shotKey(m.number, s.number)));
export type ShotPhoto = { id: string; module_number: number; slide_number: number; filename: string; mime_type: string; size: number; has_thumbnail: number; uploaded_at: string; uploaded_by: string; uploader_name: string };
export type ShotState = { module_number: number; slide_number: number; status: "todo" | "complete" | "unavailable"; note: string; updated_at: string };
export type ShotData = { photos: ShotPhoto[]; states: ShotState[] };
