import {applicationCopy} from './locales/application';
import { additionalCopy } from "./locales";
import { authCopy } from './auth-copy';
import { languageLocale, type ContentLanguage, type Language } from "./i18n";
type Dictionary = Record<string,string>;
export type LocalizedText=string|{key:string;values?:Record<string,string|number>};
export const ui: Record<Exclude<ContentLanguage,"en">,Dictionary> = {
  nl: additionalCopy.nl.ui,
  pt: additionalCopy.pt.ui,
  pl: additionalCopy.pl.ui,
  ro: additionalCopy.ro.ui,
  cs: additionalCopy.cs.ui,
  sk: additionalCopy.sk.ui,
  sl: additionalCopy.sl.ui,
  hu: additionalCopy.hu.ui,
  ar: additionalCopy.ar.ui,
  es:{
    "Learner view":"Vista del alumno","Reporting":"Informes","Working prototype · Fictional learner data · Sample training content":"Prototipo · Datos ficticios · Formación de muestra",
    "FOR NEW STORE COLLEAGUES":"PARA NUEVOS EMPLEADOS DE TIENDA","Start safe.":"Empieza con seguridad.","Feel ready for day one.":"Prepárate para tu primer día.","Six short chapters, one quick assessment, and a pass to show your manager.":"Seis capítulos breves, una evaluación y un pase para mostrar a tu responsable.",
    "Choose your store":"Elige tu tienda","Learn at your pace":"Aprende a tu ritmo","Show your pass":"Muestra tu pase","Your progress is saved so you can come back.":"Guardamos tu progreso para que puedas volver.",
    "I’m new here":"Soy nuevo/a","I have a code":"Tengo un código","Let’s get you started":"Empecemos","Your pass code will appear as soon as you continue.":"Tu código de acceso aparecerá al continuar.","Full name":"Nombre completo","Email address":"Correo electrónico","Country":"País","Primark store":"Tienda Primark","Choose a country":"Elige un país","Get started":"Empezar","Welcome back":"Bienvenido/a de nuevo","Use the code you saved when you first joined.":"Usa el código que guardaste al registrarte.","Pass code":"Código de acceso","Continue learning":"Continuar aprendiendo","Code recovery by email is not connected in this private prototype.":"La recuperación por correo aún no está conectada en este prototipo privado.",
    "YOUR INDUCTION":"TU FORMACIÓN INICIAL","Overview":"Resumen","Assessment":"Evaluación","My Safety Passport":"Mi pasaporte de seguridad","Sign out":"Cerrar sesión","Your pass code:":"Tu código:","Save it to sign in on another device.":"Guárdalo para entrar desde otro dispositivo.","Copy code":"Copiar código","YOUR FIRST STEP AT PRIMARK":"TU PRIMER PASO EN PRIMARK","Hello,":"Hola,","Learn in any order. Come back whenever you need to.":"Aprende en cualquier orden. Vuelve cuando lo necesites.","chapters viewed":"capítulos vistos","Your progress":"Tu progreso","Safety Passport ready":"Pasaporte de seguridad listo","Assessment passed · view every chapter to finish":"Evaluación superada · mira todos los capítulos para terminar","View all chapters and score at least 90%":"Mira todos los capítulos y consigue al menos un 90%","A completion from the previous LMS is on your record, shown separately.":"Tienes una finalización del sistema anterior, mostrada por separado.","Your Primark Safety Passport is ready":"Tu Primark Safety Passport está listo","Show it to your manager on day one":"Muéstralo a tu responsable el primer día.","Six short chapters":"Seis capítulos breves","Choose where to begin":"Elige por dónde empezar","Viewed":"Visto","View again":"Ver de nuevo","Open chapter":"Abrir capítulo","Final assessment":"Evaluación final","20 sample questions · Pass at 18/20 · Retry straight away":"20 preguntas de muestra · Aprueba con 18/20 · Reintento inmediato","Open assessment":"Abrir evaluación",
    "All chapters":"Todos los capítulos","SYNTHESIA VIDEO GOES HERE":"AQUÍ IRÁ EL VÍDEO DE SYNTHESIA","SAMPLE CHAPTER · VIDEO CONTENT WILL BE ADDED LATER":"CAPÍTULO DE MUESTRA · EL VÍDEO SE AÑADIRÁ DESPUÉS","estimated":"estimados","Remember":"Recuerda","Next chapter":"Siguiente capítulo","Mark sample chapter viewed":"Marcar capítulo de muestra como visto","You can open any chapter at any time.":"Puedes abrir cualquier capítulo cuando quieras.","Back to induction":"Volver a la formación","FINAL ASSESSMENT · SAMPLE QUESTIONS":"EVALUACIÓN FINAL · PREGUNTAS DE MUESTRA","Show what you know.":"Demuestra lo que sabes.","Answer all 20 questions. You need 18 correct to pass.":"Responde las 20 preguntas. Necesitas 18 aciertos para aprobar.","Question":"Pregunta","of":"de","answered":"respondidas","Previous":"Anterior","Next question":"Siguiente pregunta","Submit answers":"Enviar respuestas","ASSESSMENT RESULT":"RESULTADO DE LA EVALUACIÓN","You passed. Well done.":"Has aprobado. ¡Bien hecho!","You can try again.":"Puedes intentarlo de nuevo.","You scored":"Has obtenido","The pass mark is 18/20.":"Se aprueba con 18/20.","View all six chapters to get your Safety Passport.":"Mira los seis capítulos para obtener tu pasaporte de seguridad.","Back to chapters":"Volver a los capítulos","Retry assessment":"Reintentar evaluación","View my pass":"Ver mi pase","Your pass is almost ready":"Tu pase está casi listo","View all six chapters and pass the assessment.":"Mira los seis capítulos y aprueba la evaluación.",
    "Print or save PDF":"Imprimir o guardar PDF","HEALTH, SAFETY & ENVIRONMENT":"SALUD, SEGURIDAD Y MEDIOAMBIENTE","CERTIFICATE OF COMPLETION":"CERTIFICADO DE FINALIZACIÓN","Primark Safety Passport":"Primark Safety Passport","Ready to show your site manager on day one.":"Listo para mostrar a tu responsable el primer día.","AWARDED TO":"OTORGADO A","DATE PASSED":"FECHA DE APROBACIÓN","ASSESSMENT":"EVALUACIÓN","Passed":"Aprobado","Scan to verify":"Escanear para verificar","Scan to view this live certificate record.":"Escanea para ver el registro vigente del certificado.","Certificate ID":"ID del certificado","Print / Save PDF":"Imprimir / Guardar PDF","Keep this pass ready for your first day.":"Ten este pase a mano para tu primer día.",
    "PRIMARK · INDUCTION OVERSIGHT":"PRIMARK · SEGUIMIENTO DE FORMACIÓN","New starter progress":"Progreso de nuevos empleados","See who has entered, started and completed the new induction.":"Consulta quién se ha registrado, comenzado y completado la formación.","Load sample learners":"Cargar alumnos de muestra","Export CSV":"Exportar CSV","Demo reporting view":"Vista de informes de demostración","Global":"Global","Store":"Tienda","Entered":"Registrados","Started":"Iniciados","Completed":"Finalizados","Previous LMS":"Sistema anterior","Created a pass":"Han creado un pase","Opened learning or assessment":"Han abierto contenido o evaluación","Six chapters + 90% pass":"Seis capítulos + 90%","Historical completions · separate":"Finalizaciones históricas · separadas","By country":"Por país","By store":"Por tienda","New app activity":"Actividad de la nueva app","How the counts work":"Cómo se calculan los totales","A person created their pass in this app.":"Una persona creó su pase en esta app.","They opened a chapter or assessment.":"Abrió un capítulo o la evaluación.","Six chapters viewed and 90% achieved.":"Vio seis capítulos y obtuvo un 90%.","Imported completions stay separate.":"Las finalizaciones importadas se muestran aparte.","Learners":"Alumnos","Names and progress in this reporting view":"Nombres y progreso de esta vista","Search learners":"Buscar alumnos","Status":"Estado","Score":"Puntuación","Old LMS":"Sistema anterior","In progress":"En curso","Not started":"Sin comenzar","No learners match this view.":"No hay alumnos que coincidan.","No joiners in this view yet. Load sample learners to explore.":"Aún no hay alumnos aquí. Carga los datos de muestra.","Import previous LMS completions":"Importar finalizaciones anteriores","Choose CSV file":"Elegir archivo CSV","Import CSV":"Importar CSV","The role switcher illustrates scoped reporting. Production managers will need individual accounts and permissions.":"El selector de roles ilustra el alcance de los informes. Los responsables necesitarán cuentas y permisos individuales.","Private working prototype · Sample content is not approved training":"Prototipo privado · El contenido de muestra no es formación aprobada",
    "LIVE CERTIFICATE RECORD":"REGISTRO VIGENTE DEL CERTIFICADO","Safety Passport verified":"Pasaporte de seguridad verificado","This person completed the Primark induction in this prototype.":"Esta persona completó la formación de Primark en este prototipo.","Name":"Nombre","Pass not found":"Pase no encontrado","We could not verify a completed pass with this code.":"No hemos podido verificar un pase con este código.","Private prototype · Sample learning and demo records":"Prototipo privado · Formación y registros de muestra",
    "CHAPTER":"CAPÍTULO","OF 06":"DE 06","Loading induction…":"Cargando formación…","Your full name":"Tu nombre completo","Yes":"Sí","CSV columns:":"Columnas CSV:","Completed accepts 1 or 0. Date and store ID are optional.":"completed acepta 1 o 0. La fecha y el ID de tienda son opcionales.","historical rows imported.":"registros históricos importados.","QR code to verify the Safety Passport":"Código QR para verificar el pasaporte de seguridad"
  },
  fr:{
    "Learner view":"Espace apprenant","Reporting":"Rapports","Working prototype · Fictional learner data · Sample training content":"Prototype · Données fictives · Contenu de formation d’exemple",
    "FOR NEW STORE COLLEAGUES":"POUR LES NOUVEAUX COLLÈGUES EN MAGASIN","Start safe.":"Commencez en sécurité.","Feel ready for day one.":"Soyez prêt dès le premier jour.","Six short chapters, one quick assessment, and a pass to show your manager.":"Six chapitres courts, une évaluation et un pass à montrer à votre responsable.","Choose your store":"Choisissez votre magasin","Learn at your pace":"Apprenez à votre rythme","Show your pass":"Montrez votre pass","Your progress is saved so you can come back.":"Votre progression est enregistrée pour que vous puissiez revenir.",
    "I’m new here":"Je débute","I have a code":"J’ai un code","Let’s get you started":"Commençons","Your pass code will appear as soon as you continue.":"Votre code d’accès s’affichera après cette étape.","Full name":"Nom complet","Email address":"Adresse e-mail","Country":"Pays","Primark store":"Magasin Primark","Choose a country":"Choisissez un pays","Get started":"Commencer","Welcome back":"Bon retour","Use the code you saved when you first joined.":"Utilisez le code conservé lors de votre inscription.","Pass code":"Code d’accès","Continue learning":"Reprendre la formation","Code recovery by email is not connected in this private prototype.":"La récupération par e-mail n’est pas encore activée dans ce prototype privé.",
    "YOUR INDUCTION":"VOTRE FORMATION INITIALE","Overview":"Vue d’ensemble","Assessment":"Évaluation","My Safety Passport":"Mon passeport de sécurité","Sign out":"Se déconnecter","Your pass code:":"Votre code :","Save it to sign in on another device.":"Conservez-le pour vous connecter sur un autre appareil.","Copy code":"Copier le code","YOUR FIRST STEP AT PRIMARK":"VOTRE PREMIER PAS CHEZ PRIMARK","Hello,":"Bonjour,","Learn in any order. Come back whenever you need to.":"Suivez les chapitres dans l’ordre de votre choix. Revenez quand vous voulez.","chapters viewed":"chapitres vus","Your progress":"Votre progression","Safety Passport ready":"Passeport de sécurité prêt","Assessment passed · view every chapter to finish":"Évaluation réussie · regardez tous les chapitres pour terminer","View all chapters and score at least 90%":"Regardez tous les chapitres et obtenez au moins 90 %","A completion from the previous LMS is on your record, shown separately.":"Une formation terminée dans l’ancien système figure séparément dans votre dossier.","Your Primark Safety Passport is ready":"Votre Primark Safety Passport est prêt","Show it to your manager on day one":"Montrez-le à votre responsable le premier jour.","Six short chapters":"Six chapitres courts","Choose where to begin":"Choisissez par où commencer","Viewed":"Vu","View again":"Revoir","Open chapter":"Ouvrir le chapitre","Final assessment":"Évaluation finale","20 sample questions · Pass at 18/20 · Retry straight away":"20 questions d’exemple · Réussite à 18/20 · Nouvel essai immédiat","Open assessment":"Ouvrir l’évaluation",
    "All chapters":"Tous les chapitres","SYNTHESIA VIDEO GOES HERE":"LA VIDÉO SYNTHESIA SERA ICI","SAMPLE CHAPTER · VIDEO CONTENT WILL BE ADDED LATER":"CHAPITRE D’EXEMPLE · VIDÉO À VENIR","estimated":"estimées","Remember":"À retenir","Next chapter":"Chapitre suivant","Mark sample chapter viewed":"Marquer le chapitre d’exemple comme vu","You can open any chapter at any time.":"Vous pouvez ouvrir n’importe quel chapitre à tout moment.","Back to induction":"Retour à la formation","FINAL ASSESSMENT · SAMPLE QUESTIONS":"ÉVALUATION FINALE · QUESTIONS D’EXEMPLE","Show what you know.":"Montrez ce que vous savez.","Answer all 20 questions. You need 18 correct to pass.":"Répondez aux 20 questions. Il faut 18 bonnes réponses pour réussir.","Question":"Question","of":"sur","answered":"répondues","Previous":"Précédent","Next question":"Question suivante","Submit answers":"Envoyer les réponses","ASSESSMENT RESULT":"RÉSULTAT DE L’ÉVALUATION","You passed. Well done.":"Vous avez réussi. Bravo !","You can try again.":"Vous pouvez réessayer.","You scored":"Vous avez obtenu","The pass mark is 18/20.":"Le seuil de réussite est de 18/20.","View all six chapters to get your Safety Passport.":"Regardez les six chapitres pour obtenir votre passeport de sécurité.","Back to chapters":"Retour aux chapitres","Retry assessment":"Réessayer l’évaluation","View my pass":"Voir mon pass","Your pass is almost ready":"Votre pass est presque prêt","View all six chapters and pass the assessment.":"Regardez les six chapitres et réussissez l’évaluation.",
    "Print or save PDF":"Imprimer ou enregistrer en PDF","HEALTH, SAFETY & ENVIRONMENT":"SANTÉ, SÉCURITÉ ET ENVIRONNEMENT","CERTIFICATE OF COMPLETION":"ATTESTATION DE FORMATION","Primark Safety Passport":"Primark Safety Passport","Ready to show your site manager on day one.":"À présenter à votre responsable le premier jour.","AWARDED TO":"DÉCERNÉ À","DATE PASSED":"DATE DE RÉUSSITE","ASSESSMENT":"ÉVALUATION","Passed":"Réussi","Scan to verify":"Scanner pour vérifier","Scan to view this live certificate record.":"Scannez pour consulter l’attestation en ligne.","Certificate ID":"ID de l’attestation","Print / Save PDF":"Imprimer / Enregistrer en PDF","Keep this pass ready for your first day.":"Gardez ce pass à portée de main pour votre premier jour.",
    "PRIMARK · INDUCTION OVERSIGHT":"PRIMARK · SUIVI DE LA FORMATION","New starter progress":"Progression des nouveaux collègues","See who has entered, started and completed the new induction.":"Consultez les inscriptions, débuts et achèvements de la formation.","Load sample learners":"Charger les apprenants d’exemple","Export CSV":"Exporter le CSV","Demo reporting view":"Vue de démonstration","Global":"Global","Store":"Magasin","Entered":"Inscrits","Started":"Commencé","Completed":"Terminés","Previous LMS":"Ancien système","Created a pass":"Ont créé un pass","Opened learning or assessment":"Ont ouvert un chapitre ou l’évaluation","Six chapters + 90% pass":"Six chapitres + 90 %","Historical completions · separate":"Formations antérieures · séparées","By country":"Par pays","By store":"Par magasin","New app activity":"Activité de la nouvelle app","How the counts work":"Comprendre les chiffres","A person created their pass in this app.":"Une personne a créé son pass dans cette app.","They opened a chapter or assessment.":"Elle a ouvert un chapitre ou l’évaluation.","Six chapters viewed and 90% achieved.":"Six chapitres vus et 90 % obtenus.","Imported completions stay separate.":"Les formations importées restent séparées.","Learners":"Apprenants","Names and progress in this reporting view":"Noms et progression de cette vue","Search learners":"Rechercher","Status":"Statut","Score":"Score","Old LMS":"Ancien système","In progress":"En cours","Not started":"Non commencé","No learners match this view.":"Aucun apprenant ne correspond.","No joiners in this view yet. Load sample learners to explore.":"Aucun nouvel arrivant ici. Chargez les exemples.","Import previous LMS completions":"Importer les formations antérieures","Choose CSV file":"Choisir un CSV","Import CSV":"Importer le CSV","The role switcher illustrates scoped reporting. Production managers will need individual accounts and permissions.":"Le sélecteur de rôle illustre les vues limitées. Les responsables auront besoin de comptes et droits individuels.","Private working prototype · Sample content is not approved training":"Prototype privé · Le contenu d’exemple n’est pas une formation validée",
    "LIVE CERTIFICATE RECORD":"ATTESTATION EN LIGNE","Safety Passport verified":"Passeport de sécurité vérifié","This person completed the Primark induction in this prototype.":"Cette personne a terminé la formation Primark dans ce prototype.","Name":"Nom","Pass not found":"Pass introuvable","We could not verify a completed pass with this code.":"Nous n’avons pas pu vérifier de pass avec ce code.","Private prototype · Sample learning and demo records":"Prototype privé · Formations et dossiers d’exemple",
    "CHAPTER":"CHAPITRE","OF 06":"SUR 06","Loading induction…":"Chargement de la formation…","Your full name":"Votre nom complet","Yes":"Oui","CSV columns:":"Colonnes CSV :","Completed accepts 1 or 0. Date and store ID are optional.":"completed accepte 1 ou 0. La date et l’ID du magasin sont facultatifs.","historical rows imported.":"lignes historiques importées.","QR code to verify the Safety Passport":"Code QR pour vérifier le passeport de sécurité"
  },
  de:{
    "Learner view":"Lernansicht","Reporting":"Berichte","Working prototype · Fictional learner data · Sample training content":"Prototyp · Fiktive Lerndaten · Beispielinhalte",
    "FOR NEW STORE COLLEAGUES":"FÜR NEUE MITARBEITENDE IN DER FILIALE","Start safe.":"Sicher starten.","Feel ready for day one.":"Bereit für den ersten Tag.","Six short chapters, one quick assessment, and a pass to show your manager.":"Sechs kurze Kapitel, ein Test und ein Nachweis für Ihre Führungskraft.","Choose your store":"Filiale auswählen","Learn at your pace":"Im eigenen Tempo lernen","Show your pass":"Nachweis vorzeigen","Your progress is saved so you can come back.":"Ihr Fortschritt wird gespeichert, damit Sie später fortfahren können.",
    "I’m new here":"Ich bin neu","I have a code":"Ich habe einen Code","Let’s get you started":"Los geht’s","Your pass code will appear as soon as you continue.":"Ihr Zugangscode erscheint direkt nach dem Fortfahren.","Full name":"Vollständiger Name","Email address":"E-Mail-Adresse","Country":"Land","Primark store":"Primark Filiale","Choose a country":"Land auswählen","Get started":"Loslegen","Welcome back":"Willkommen zurück","Use the code you saved when you first joined.":"Verwenden Sie den Code, den Sie bei der Anmeldung gespeichert haben.","Pass code":"Zugangscode","Continue learning":"Weiterlernen","Code recovery by email is not connected in this private prototype.":"Die Code-Wiederherstellung per E-Mail ist in diesem privaten Prototyp noch nicht verbunden.",
    "YOUR INDUCTION":"IHRE EINFÜHRUNG","Overview":"Übersicht","Assessment":"Test","My Safety Passport":"Mein Sicherheitspass","Sign out":"Abmelden","Your pass code:":"Ihr Code:","Save it to sign in on another device.":"Speichern Sie ihn für die Anmeldung auf einem anderen Gerät.","Copy code":"Code kopieren","YOUR FIRST STEP AT PRIMARK":"IHR ERSTER SCHRITT BEI PRIMARK","Hello,":"Hallo,","Learn in any order. Come back whenever you need to.":"Lernen Sie in beliebiger Reihenfolge und kommen Sie jederzeit zurück.","chapters viewed":"Kapitel angesehen","Your progress":"Ihr Fortschritt","Safety Passport ready":"Sicherheitspass bereit","Assessment passed · view every chapter to finish":"Test bestanden · sehen Sie alle Kapitel an","View all chapters and score at least 90%":"Sehen Sie alle Kapitel an und erreichen Sie mindestens 90 %","A completion from the previous LMS is on your record, shown separately.":"Ein Abschluss aus dem früheren System ist getrennt vermerkt.","Your Primark Safety Passport is ready":"Ihr Primark Safety Passport ist bereit","Show it to your manager on day one":"Zeigen Sie ihn Ihrer Führungskraft am ersten Tag.","Six short chapters":"Sechs kurze Kapitel","Choose where to begin":"Wählen Sie einen Einstieg","Viewed":"Angesehen","View again":"Erneut ansehen","Open chapter":"Kapitel öffnen","Final assessment":"Abschlusstest","20 sample questions · Pass at 18/20 · Retry straight away":"20 Beispielfragen · Bestanden ab 18/20 · Sofort erneut versuchen","Open assessment":"Test öffnen",
    "All chapters":"Alle Kapitel","SYNTHESIA VIDEO GOES HERE":"HIER FOLGT DAS SYNTHESIA VIDEO","SAMPLE CHAPTER · VIDEO CONTENT WILL BE ADDED LATER":"BEISPIELKAPITEL · VIDEO FOLGT SPÄTER","estimated":"geschätzt","Remember":"Merken Sie sich","Next chapter":"Nächstes Kapitel","Mark sample chapter viewed":"Beispielkapitel als angesehen markieren","You can open any chapter at any time.":"Sie können jedes Kapitel jederzeit öffnen.","Back to induction":"Zurück zur Einführung","FINAL ASSESSMENT · SAMPLE QUESTIONS":"ABSCHLUSSTEST · BEISPIELFRAGEN","Show what you know.":"Zeigen Sie, was Sie wissen.","Answer all 20 questions. You need 18 correct to pass.":"Beantworten Sie alle 20 Fragen. Zum Bestehen brauchen Sie 18 richtige Antworten.","Question":"Frage","of":"von","answered":"beantwortet","Previous":"Zurück","Next question":"Nächste Frage","Submit answers":"Antworten abgeben","ASSESSMENT RESULT":"TESTERGEBNIS","You passed. Well done.":"Bestanden. Gut gemacht!","You can try again.":"Sie können es erneut versuchen.","You scored":"Sie haben","The pass mark is 18/20.":"Zum Bestehen sind 18/20 nötig.","View all six chapters to get your Safety Passport.":"Sehen Sie alle sechs Kapitel an, um Ihren Sicherheitspass zu erhalten.","Back to chapters":"Zurück zu den Kapiteln","Retry assessment":"Test wiederholen","View my pass":"Nachweis ansehen","Your pass is almost ready":"Ihr Nachweis ist fast bereit","View all six chapters and pass the assessment.":"Sehen Sie alle sechs Kapitel an und bestehen Sie den Test.",
    "Print or save PDF":"Drucken oder als PDF speichern","HEALTH, SAFETY & ENVIRONMENT":"GESUNDHEIT, SICHERHEIT & UMWELT","CERTIFICATE OF COMPLETION":"TEILNAHMEBESCHEINIGUNG","Primark Safety Passport":"Primark Safety Passport","Ready to show your site manager on day one.":"Bereit zum Vorzeigen am ersten Tag.","AWARDED TO":"AUSGESTELLT FÜR","DATE PASSED":"BESTANDEN AM","ASSESSMENT":"TEST","Passed":"Bestanden","Scan to verify":"Zur Prüfung scannen","Scan to view this live certificate record.":"Scannen Sie den Code, um den aktuellen Nachweis zu sehen.","Certificate ID":"Nachweis-ID","Print / Save PDF":"Drucken / Als PDF speichern","Keep this pass ready for your first day.":"Halten Sie den Nachweis für Ihren ersten Tag bereit.",
    "PRIMARK · INDUCTION OVERSIGHT":"PRIMARK · EINARBEITUNGSÜBERSICHT","New starter progress":"Fortschritt neuer Mitarbeitender","See who has entered, started and completed the new induction.":"Sehen Sie Anmeldungen, Starts und Abschlüsse der Einführung.","Load sample learners":"Beispieldaten laden","Export CSV":"CSV exportieren","Demo reporting view":"Demo-Berichtsansicht","Global":"Global","Store":"Filiale","Entered":"Angemeldet","Started":"Begonnen","Completed":"Abgeschlossen","Previous LMS":"Früheres System","Created a pass":"Nachweis erstellt","Opened learning or assessment":"Kapitel oder Test geöffnet","Six chapters + 90% pass":"Sechs Kapitel + 90 %","Historical completions · separate":"Frühere Abschlüsse · getrennt","By country":"Nach Land","By store":"Nach Filiale","New app activity":"Aktivität in der neuen App","How the counts work":"So entstehen die Zahlen","A person created their pass in this app.":"Eine Person hat in dieser App einen Nachweis erstellt.","They opened a chapter or assessment.":"Sie hat ein Kapitel oder den Test geöffnet.","Six chapters viewed and 90% achieved.":"Sechs Kapitel angesehen und 90 % erreicht.","Imported completions stay separate.":"Importierte Abschlüsse bleiben getrennt.","Learners":"Lernende","Names and progress in this reporting view":"Namen und Fortschritt in dieser Ansicht","Search learners":"Lernende suchen","Status":"Status","Score":"Punktzahl","Old LMS":"Altes System","In progress":"In Bearbeitung","Not started":"Nicht begonnen","No learners match this view.":"Keine passenden Lernenden.","No joiners in this view yet. Load sample learners to explore.":"Noch keine neuen Mitarbeitenden in dieser Ansicht. Laden Sie Beispieldaten.","Import previous LMS completions":"Frühere Abschlüsse importieren","Choose CSV file":"CSV auswählen","Import CSV":"CSV importieren","The role switcher illustrates scoped reporting. Production managers will need individual accounts and permissions.":"Der Rollenwechsel zeigt eingeschränkte Ansichten. In der Praxis benötigen Führungskräfte eigene Konten und Rechte.","Private working prototype · Sample content is not approved training":"Privater Prototyp · Beispielinhalte sind keine freigegebene Schulung",
    "LIVE CERTIFICATE RECORD":"AKTUELLER NACHWEIS","Safety Passport verified":"Sicherheitspass bestätigt","This person completed the Primark induction in this prototype.":"Diese Person hat die Primark Einführung in diesem Prototyp abgeschlossen.","Name":"Name","Pass not found":"Nachweis nicht gefunden","We could not verify a completed pass with this code.":"Mit diesem Code konnte kein Abschluss bestätigt werden.","Private prototype · Sample learning and demo records":"Privater Prototyp · Beispielinhalte und Testdaten",
    "CHAPTER":"KAPITEL","OF 06":"VON 06","Loading induction…":"Einführung wird geladen…","Your full name":"Ihr vollständiger Name","Yes":"Ja","CSV columns:":"CSV-Spalten:","Completed accepts 1 or 0. Date and store ID are optional.":"completed akzeptiert 1 oder 0. Datum und Filial-ID sind optional.","historical rows imported.":"historische Einträge importiert.","QR code to verify the Safety Passport":"QR-Code zur Überprüfung des Sicherheitspasses"
  },
  it:{
    "Learner view":"Area formazione","Reporting":"Report","Working prototype · Fictional learner data · Sample training content":"Prototipo · Dati fittizi · Contenuti formativi di esempio",
    "FOR NEW STORE COLLEAGUES":"PER I NUOVI COLLEGHI IN NEGOZIO","Start safe.":"Inizia in sicurezza.","Feel ready for day one.":"Preparati al primo giorno.","Six short chapters, one quick assessment, and a pass to show your manager.":"Sei brevi capitoli, una verifica e un attestato da mostrare al responsabile.","Choose your store":"Scegli il negozio","Learn at your pace":"Impara al tuo ritmo","Show your pass":"Mostra l’attestato","Your progress is saved so you can come back.":"I tuoi progressi vengono salvati, così puoi tornare quando vuoi.",
    "I’m new here":"Sono nuovo/a","I have a code":"Ho un codice","Let’s get you started":"Cominciamo","Your pass code will appear as soon as you continue.":"Il tuo codice di accesso apparirà appena prosegui.","Full name":"Nome e cognome","Email address":"Indirizzo e-mail","Country":"Paese","Primark store":"Negozio Primark","Choose a country":"Scegli un paese","Get started":"Inizia","Welcome back":"Bentornato/a","Use the code you saved when you first joined.":"Usa il codice salvato al primo accesso.","Pass code":"Codice di accesso","Continue learning":"Continua la formazione","Code recovery by email is not connected in this private prototype.":"Il recupero del codice via e-mail non è ancora attivo in questo prototipo privato.",
    "YOUR INDUCTION":"LA TUA FORMAZIONE INIZIALE","Overview":"Panoramica","Assessment":"Verifica","My Safety Passport":"Il mio passaporto della sicurezza","Sign out":"Esci","Your pass code:":"Il tuo codice:","Save it to sign in on another device.":"Salvalo per accedere da un altro dispositivo.","Copy code":"Copia codice","YOUR FIRST STEP AT PRIMARK":"IL TUO PRIMO PASSO IN PRIMARK","Hello,":"Ciao,","Learn in any order. Come back whenever you need to.":"Segui i capitoli nell’ordine che preferisci. Torna quando vuoi.","chapters viewed":"capitoli visti","Your progress":"I tuoi progressi","Safety Passport ready":"Passaporto della sicurezza pronto","Assessment passed · view every chapter to finish":"Verifica superata · guarda tutti i capitoli per finire","View all chapters and score at least 90%":"Guarda tutti i capitoli e ottieni almeno il 90%","A completion from the previous LMS is on your record, shown separately.":"Nel tuo profilo compare separatamente un completamento del vecchio sistema.","Your Primark Safety Passport is ready":"Il tuo Primark Safety Passport è pronto","Show it to your manager on day one":"Mostralo al responsabile il primo giorno.","Six short chapters":"Sei brevi capitoli","Choose where to begin":"Scegli da dove iniziare","Viewed":"Visto","View again":"Rivedi","Open chapter":"Apri capitolo","Final assessment":"Verifica finale","20 sample questions · Pass at 18/20 · Retry straight away":"20 domande di esempio · Supera con 18/20 · Riprova subito","Open assessment":"Apri la verifica",
    "All chapters":"Tutti i capitoli","SYNTHESIA VIDEO GOES HERE":"QUI SARÀ INSERITO IL VIDEO SYNTHESIA","SAMPLE CHAPTER · VIDEO CONTENT WILL BE ADDED LATER":"CAPITOLO DI ESEMPIO · VIDEO IN ARRIVO","estimated":"stimati","Remember":"Ricorda","Next chapter":"Capitolo successivo","Mark sample chapter viewed":"Segna il capitolo di esempio come visto","You can open any chapter at any time.":"Puoi aprire qualsiasi capitolo quando vuoi.","Back to induction":"Torna alla formazione","FINAL ASSESSMENT · SAMPLE QUESTIONS":"VERIFICA FINALE · DOMANDE DI ESEMPIO","Show what you know.":"Mostra ciò che sai.","Answer all 20 questions. You need 18 correct to pass.":"Rispondi a tutte le 20 domande. Per superare la verifica servono 18 risposte corrette.","Question":"Domanda","of":"di","answered":"risposte","Previous":"Precedente","Next question":"Domanda successiva","Submit answers":"Invia risposte","ASSESSMENT RESULT":"RISULTATO DELLA VERIFICA","You passed. Well done.":"Hai superato la verifica. Ben fatto!","You can try again.":"Puoi riprovare.","You scored":"Hai ottenuto","The pass mark is 18/20.":"Si supera con 18/20.","View all six chapters to get your Safety Passport.":"Guarda tutti e sei i capitoli per ottenere il passaporto della sicurezza.","Back to chapters":"Torna ai capitoli","Retry assessment":"Riprova la verifica","View my pass":"Vedi l’attestato","Your pass is almost ready":"Il tuo attestato è quasi pronto","View all six chapters and pass the assessment.":"Guarda tutti i sei capitoli e supera la verifica.",
    "Print or save PDF":"Stampa o salva PDF","HEALTH, SAFETY & ENVIRONMENT":"SALUTE, SICUREZZA E AMBIENTE","CERTIFICATE OF COMPLETION":"ATTESTATO DI COMPLETAMENTO","Primark Safety Passport":"Primark Safety Passport","Ready to show your site manager on day one.":"Pronto da mostrare al responsabile il primo giorno.","AWARDED TO":"RILASCIATO A","DATE PASSED":"DATA DI SUPERAMENTO","ASSESSMENT":"VERIFICA","Passed":"Superato","Scan to verify":"Scansiona per verificare","Scan to view this live certificate record.":"Scansiona per consultare l’attestato aggiornato.","Certificate ID":"ID attestato","Print / Save PDF":"Stampa / Salva PDF","Keep this pass ready for your first day.":"Tieni l’attestato pronto per il primo giorno.",
    "PRIMARK · INDUCTION OVERSIGHT":"PRIMARK · MONITORAGGIO FORMAZIONE","New starter progress":"Progressi dei nuovi assunti","See who has entered, started and completed the new induction.":"Consulta chi si è registrato, ha iniziato e ha completato la formazione.","Load sample learners":"Carica utenti di esempio","Export CSV":"Esporta CSV","Demo reporting view":"Vista report dimostrativa","Global":"Globale","Store":"Negozio","Entered":"Registrati","Started":"Iniziati","Completed":"Completati","Previous LMS":"Sistema precedente","Created a pass":"Hanno creato l’attestato","Opened learning or assessment":"Hanno aperto contenuti o verifica","Six chapters + 90% pass":"Sei capitoli + 90%","Historical completions · separate":"Completamenti storici · separati","By country":"Per paese","By store":"Per negozio","New app activity":"Attività della nuova app","How the counts work":"Come si calcolano i totali","A person created their pass in this app.":"Una persona ha creato l’attestato in questa app.","They opened a chapter or assessment.":"Ha aperto un capitolo o la verifica.","Six chapters viewed and 90% achieved.":"Ha visto sei capitoli e ottenuto il 90%.","Imported completions stay separate.":"I completamenti importati restano separati.","Learners":"Utenti","Names and progress in this reporting view":"Nomi e progressi in questa vista","Search learners":"Cerca utenti","Status":"Stato","Score":"Punteggio","Old LMS":"Vecchio sistema","In progress":"In corso","Not started":"Non iniziato","No learners match this view.":"Nessun utente corrisponde.","No joiners in this view yet. Load sample learners to explore.":"Nessun nuovo assunto qui. Carica gli utenti di esempio.","Import previous LMS completions":"Importa completamenti precedenti","Choose CSV file":"Scegli file CSV","Import CSV":"Importa CSV","The role switcher illustrates scoped reporting. Production managers will need individual accounts and permissions.":"Il selettore dei ruoli illustra le viste limitate. In produzione serviranno account e permessi individuali.","Private working prototype · Sample content is not approved training":"Prototipo privato · Il contenuto di esempio non è formazione approvata",
    "LIVE CERTIFICATE RECORD":"ATTESTATO ATTUALE","Safety Passport verified":"Passaporto della sicurezza verificato","This person completed the Primark induction in this prototype.":"Questa persona ha completato la formazione Primark in questo prototipo.","Name":"Nome","Pass not found":"Attestato non trovato","We could not verify a completed pass with this code.":"Non è stato possibile verificare un attestato con questo codice.","Private prototype · Sample learning and demo records":"Prototipo privato · Formazione e dati di esempio",
    "CHAPTER":"CAPITOLO","OF 06":"DI 06","Loading induction…":"Caricamento formazione…","Your full name":"Nome e cognome","Yes":"Sì","CSV columns:":"Colonne CSV:","Completed accepts 1 or 0. Date and store ID are optional.":"completed accetta 1 o 0. Data e ID del negozio sono opzionali.","historical rows imported.":"righe storiche importate.","QR code to verify the Safety Passport":"Codice QR per verificare il passaporto della sicurezza"
  }
};
const extra: Record<"es"|"fr"|"de"|"it",Dictionary> = {
  es: {
    "YOUR LEARNING":"TU FORMACIÓN","My Courses":"Mis cursos","Safety Passport":"Pasaporte de seguridad","More courses":"Más cursos","Coming soon":"Próximamente","Available now":"Disponible ahora","Includes a practical element":"Incluye una parte práctica",
    "Manual Handling":"Manipulación manual de cargas","Security, loss prevention and personal safety":"Seguridad, prevención de pérdidas y seguridad personal","Code of Conduct and Speak Up":"Código de conducta y comunicación de inquietudes","Dignity at Work":"Respeto en el trabajo","Data protection":"Protección de datos","Customer service and accessibility":"Atención al cliente y accesibilidad","Safeguarding and emergency procedures":"Protección de personas y procedimientos de emergencia",
    "This is an introduction only. Manual Handling is a separate course with a practical element.":"Esto es solo una introducción. La manipulación manual de cargas es un curso aparte con una parte práctica.",
    "Filter by location and date to see activity over time.":"Filtra por lugar y fecha para ver la actividad a lo largo del tiempo.","Reporting view":"Vista de informes","Year":"Año","Month":"Mes","All time":"Todo el periodo","All months":"Todos los meses","All recorded activity":"Toda la actividad registrada","Joined in period":"Registrados en el periodo","Started in period":"Iniciados en el periodo","Completed in period":"Finalizados en el periodo","All historical completions":"Todos los resultados históricos","Dated historical completions":"Resultados históricos con fecha","Monthly trend":"Tendencia mensual","Last 12 months":"Últimos 12 meses","Monthly trend of entries, starts and completions":"Tendencia mensual de registros, inicios y finalizaciones",
    "People who created a pass in the selected period.":"Personas que crearon un pase en el periodo seleccionado.","People who first started in the selected period.":"Personas que empezaron por primera vez en el periodo seleccionado.","People who completed in the selected period.":"Personas que finalizaron en el periodo seleccionado.","Dated imports follow the filter; undated imports appear in All time.":"Las importaciones con fecha siguen el filtro; las que no tienen fecha aparecen en Todo el periodo."
  },
  fr: {
    "YOUR LEARNING":"VOTRE FORMATION","My Courses":"Mes cours","Safety Passport":"Passeport de sécurité","More courses":"Autres cours","Coming soon":"À venir","Available now":"Disponible","Includes a practical element":"Comprend une partie pratique",
    "Manual Handling":"Manutention manuelle","Security, loss prevention and personal safety":"Sécurité, prévention des pertes et sécurité personnelle","Code of Conduct and Speak Up":"Code de conduite et signalement","Dignity at Work":"Respect au travail","Data protection":"Protection des données","Customer service and accessibility":"Service client et accessibilité","Safeguarding and emergency procedures":"Protection des personnes et procédures d’urgence",
    "This is an introduction only. Manual Handling is a separate course with a practical element.":"Ceci est une introduction. La manutention manuelle est un cours distinct avec une partie pratique.",
    "Filter by location and date to see activity over time.":"Filtrez par lieu et par date pour suivre l’activité dans le temps.","Reporting view":"Vue des rapports","Year":"Année","Month":"Mois","All time":"Toutes les dates","All months":"Tous les mois","All recorded activity":"Toute l’activité enregistrée","Joined in period":"Inscriptions sur la période","Started in period":"Démarrages sur la période","Completed in period":"Achèvements sur la période","All historical completions":"Tous les achèvements historiques","Dated historical completions":"Achèvements historiques datés","Monthly trend":"Évolution mensuelle","Last 12 months":"12 derniers mois","Monthly trend of entries, starts and completions":"Évolution mensuelle des inscriptions, débuts et achèvements",
    "People who created a pass in the selected period.":"Personnes ayant créé un pass pendant la période choisie.","People who first started in the selected period.":"Personnes ayant commencé pendant la période choisie.","People who completed in the selected period.":"Personnes ayant terminé pendant la période choisie.","Dated imports follow the filter; undated imports appear in All time.":"Les imports datés suivent le filtre ; ceux sans date figurent dans Toutes les dates."
  },
  de: {
    "YOUR LEARNING":"IHRE KURSE","My Courses":"Meine Kurse","Safety Passport":"Sicherheitspass","More courses":"Weitere Kurse","Coming soon":"Demnächst","Available now":"Jetzt verfügbar","Includes a practical element":"Mit praktischem Teil",
    "Manual Handling":"Manuelle Handhabung","Security, loss prevention and personal safety":"Sicherheit, Verlustprävention und persönliche Sicherheit","Code of Conduct and Speak Up":"Verhaltenskodex und Bedenken melden","Dignity at Work":"Respekt am Arbeitsplatz","Data protection":"Datenschutz","Customer service and accessibility":"Kundenservice und Barrierefreiheit","Safeguarding and emergency procedures":"Schutz hilfsbedürftiger Personen und Notfallverfahren",
    "This is an introduction only. Manual Handling is a separate course with a practical element.":"Dies ist nur eine Einführung. Manuelle Handhabung ist ein eigener Kurs mit praktischem Teil.",
    "Filter by location and date to see activity over time.":"Filtern Sie nach Standort und Datum, um die Entwicklung zu sehen.","Reporting view":"Berichtsansicht","Year":"Jahr","Month":"Monat","All time":"Gesamter Zeitraum","All months":"Alle Monate","All recorded activity":"Alle erfassten Aktivitäten","Joined in period":"Anmeldungen im Zeitraum","Started in period":"Starts im Zeitraum","Completed in period":"Abschlüsse im Zeitraum","All historical completions":"Alle früheren Abschlüsse","Dated historical completions":"Datierte frühere Abschlüsse","Monthly trend":"Monatlicher Verlauf","Last 12 months":"Letzte 12 Monate","Monthly trend of entries, starts and completions":"Monatlicher Verlauf von Anmeldungen, Starts und Abschlüssen",
    "People who created a pass in the selected period.":"Personen, die im gewählten Zeitraum einen Nachweis angelegt haben.","People who first started in the selected period.":"Personen, die im gewählten Zeitraum erstmals begonnen haben.","People who completed in the selected period.":"Personen, die im gewählten Zeitraum abgeschlossen haben.","Dated imports follow the filter; undated imports appear in All time.":"Datierte Importe folgen dem Filter; undatierte erscheinen unter Gesamter Zeitraum."
  },
  it: {
    "YOUR LEARNING":"LA TUA FORMAZIONE","My Courses":"I miei corsi","Safety Passport":"Passaporto della sicurezza","More courses":"Altri corsi","Coming soon":"Prossimamente","Available now":"Disponibile ora","Includes a practical element":"Include una parte pratica",
    "Manual Handling":"Movimentazione manuale","Security, loss prevention and personal safety":"Sicurezza, prevenzione delle perdite e sicurezza personale","Code of Conduct and Speak Up":"Codice di condotta e segnalazioni","Dignity at Work":"Rispetto sul lavoro","Data protection":"Protezione dei dati","Customer service and accessibility":"Servizio clienti e accessibilità","Safeguarding and emergency procedures":"Tutela delle persone e procedure di emergenza",
    "This is an introduction only. Manual Handling is a separate course with a practical element.":"Questa è solo un’introduzione. La movimentazione manuale è un corso separato con una parte pratica.",
    "Filter by location and date to see activity over time.":"Filtra per luogo e data per vedere l’andamento delle attività.","Reporting view":"Vista report","Year":"Anno","Month":"Mese","All time":"Tutto il periodo","All months":"Tutti i mesi","All recorded activity":"Tutte le attività registrate","Joined in period":"Iscritti nel periodo","Started in period":"Avvii nel periodo","Completed in period":"Completati nel periodo","All historical completions":"Tutti i completamenti precedenti","Dated historical completions":"Completamenti precedenti con data","Monthly trend":"Andamento mensile","Last 12 months":"Ultimi 12 mesi","Monthly trend of entries, starts and completions":"Andamento mensile di iscrizioni, avvii e completamenti",
    "People who created a pass in the selected period.":"Persone che hanno creato un attestato nel periodo selezionato.","People who first started in the selected period.":"Persone che hanno iniziato per la prima volta nel periodo selezionato.","People who completed in the selected period.":"Persone che hanno completato nel periodo selezionato.","Dated imports follow the filter; undated imports appear in All time.":"Le importazioni con data seguono il filtro; quelle senza data appaiono in Tutto il periodo."
  }
};
for (const lang of ["es","fr","de","it"] as const) Object.assign(ui[lang],extra[lang]);
Object.assign(ui.es,{"Language":"Idioma","Dismiss error":"Cerrar error","Prototype views":"Vistas del prototipo"});
Object.assign(ui.fr,{"Language":"Langue","Dismiss error":"Fermer l’erreur","Prototype views":"Vues du prototype"});
Object.assign(ui.de,{"Language":"Sprache","Dismiss error":"Fehler schließen","Prototype views":"Prototypansichten"});
Object.assign(ui.it,{"Language":"Lingua","Dismiss error":"Chiudi errore","Prototype views":"Viste del prototipo"});
const dictionaries=Object.fromEntries(Object.keys(ui).map(lang=>[lang,Object.fromEntries(Object.entries({...ui[lang as Exclude<Language,'en'>],...authCopy[lang as Exclude<Language,'en'>],...applicationCopy[lang as Exclude<Language,'en'>]}).map(([key,value])=>[key.toLowerCase(),value]))])) as Record<string,Dictionary>;
const aliases:Record<string,string>={"those details did not match.": "those sign-in details did not match.", "unknown action.": "invalid request.", "unknown view.": "invalid request.", "a request body is required.": "invalid request.", "unknown module.": "unknown chapter.", "invalid csv row.": "check the csv.", "invalid audience.": "choose a course audience.", "choose a country from the directory.": "choose a country", "choose a site from the directory.": "choose a site", "please use the safety passport page.": "please use the sign-in page.", "there are no users in this store yet.": "users appear here after registering for this store.", "the shot list could not be loaded. please try again.": "the shot list could not be loaded.", "this note is too long.": "keep the note to 500 characters.", "invalid slide update.": "invalid request.", "unknown module or slide.": "invalid request.", "save at least one photo before marking this slide complete.": "add a photo before marking this slide complete.", "invalid photo reference.": "invalid request.", "invalid photo part.": "invalid request.", "this photo reference is already in use.": "the photo could not be confirmed as saved. keep this page open and retry.", "the photo part is incomplete.": "the photo could not be confirmed as saved. keep this page open and retry.", "the photo preview was not valid.": "the photo could not be confirmed as saved. keep this page open and retry."};
export function translationFor(lang:Language,text:string):string|undefined{
 if(lang==='en'||!text)return text;
 const direct=dictionaries[lang]?.[aliases[text.toLowerCase()]||text.toLowerCase()];if(direct)return direct;
 // Retain presentation punctuation around a translated label, without altering IDs or data.
 const decorated=text.match(/^([←·\s]*)(.*?)([\s(:·]*)$/);
 if(decorated){const value=dictionaries[lang]?.[decorated[2].toLowerCase()];if(value)return decorated[1]+value+decorated[3];}
 return undefined;
}
export function tr(lang:Language,message:LocalizedText,values?:Record<string,string|number>){const text=typeof message==='string'?message:message.key;values=typeof message==='string'?values:message.values;const translated=translationFor(lang,text)??text;return values?translated.replace(/\{(\w+)\}/g,(match,key)=>Object.hasOwn(values,key)?String(values[key]):match):translated;}

export function formatDate(value:string|null,lang:Language){if(!value)return "—";return new Date(value).toLocaleDateString(languageLocale(lang),{day:"numeric",month:"short",year:"numeric",timeZone:"UTC"});}
const countryCodes:Record<string,string>={Austria:"AT",Bahrain:"BH",Belgium:"BE","Czech Republic":"CZ",France:"FR",Germany:"DE",Hungary:"HU",Ireland:"IE",Italy:"IT",Kuwait:"KW",Netherlands:"NL",Poland:"PL",Portugal:"PT",Romania:"RO",Slovakia:"SK",Slovenia:"SI",Spain:"ES",UAE:"AE","United Kingdom":"GB","United States":"US"};
export function countryName(country:string,lang:Language){if(lang==="en")return country;return countryCodes[country]?new Intl.DisplayNames([languageLocale(lang)],{type:"region"}).of(countryCodes[country])||country:country;}

export function formatDuration(value:string,lang:Language){return lang==="en"?value:new Intl.NumberFormat(languageLocale(lang),{style:"unit",unit:"minute",unitDisplay:"short"}).format(parseInt(value,10));}
