'use client';
import {useEffect,useState} from 'react';
import PageHeader from '@/components/page-header';
import {useLanguage} from '@/components/language-provider';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {NativeSelect} from '@/components/ui/native-select';
import type {Pathway,PathwayItem} from '@/lib/pathway-types';
import '@/components/manage-users.css';
import '@/components/pathways.css';
type Course={id:string;title:string};
type Person={id:string;name:string;email:string;workday_id:string|null;country:string};
type Data={enabled:boolean;platformAdmin:boolean;pathways?:Pathway[];courses?:Course[]};
const empty=():Pathway=>({id:'',name:'',description:'',items:[],deadline_days:null,award_certificate:false,archived:false,revision:0});
export default function PathwayAdmin(){
 const {t}=useLanguage();const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('manage'),[draft,setDraft]=useState<Pathway|null>(null),[search,setSearch]=useState(''),[courseSearch,setCourseSearch]=useState(''),[mode,setMode]=useState('any'),[pathwayId,setPathwayId]=useState(''),[personSearch,setPersonSearch]=useState(''),[people,setPeople]=useState<Person[]>([]),[selected,setSelected]=useState<Person[]>([]),[dueDate,setDueDate]=useState('');
 async function load(){const r=await fetch('/api/pathways?mode=manage',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error);setData(d);}
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 useEffect(()=>{const controller=new AbortController();const timer=setTimeout(()=>{fetch('/api/pathways?mode=people&search='+encodeURIComponent(personSearch),{signal:controller.signal,cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setPeople(d.people);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});},250);if(tab!=='assign')clearTimeout(timer);return()=>{clearTimeout(timer);controller.abort();};},[personSearch,tab]);
 async function post(body:object){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/pathways',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.error);await load();return d;}catch(e){setError((e as Error).message);return null;}finally{setBusy(false);}}
 function ordered(items:PathwayItem[],order=mode){return items.map((i,n)=>({...i,stage:order==='any'?1:order==='sequence'?n+1:order==='first'?n?2:1:i.stage}));}
 function edit(p:Pathway){setDraft({...p,items:p.items.map(i=>({...i}))});setMode('stages');setCourseSearch('');setNotice('');}
 return <div className="shell app-page course-admin"><PageHeader title={t("Learning Pathways")} view="pathways"/><main className="main manage-users pathways-page">
 <nav className="user-view-tabs pill-switch" aria-label={t('Learning Pathways')}>{['manage','assign'].map(v=><button key={v} aria-pressed={tab===v} onClick={()=>{setTab(v);setError('');setNotice('');}}>{t(v==='manage'?'Manage pathways':'Assign pathway')}</button>)}</nav>
 {error&&<p className="error" role="alert">{t(error)}</p>}{notice&&<p role="status">{notice}</p>}{!data&&!error&&<p>{t('Loading…')}</p>}
 {data&&!data.enabled&&<section className="paper pathway-panel"><h2>{t('Pathways are not enabled')}</h2><p>{t('A platform admin can enable learning pathways in Organisation settings.')}</p>{data.platformAdmin&&<a href="/admin/organisation">{t('Organisation settings')}</a>}</section>}
 {data?.enabled&&tab==='manage'&&<>
 <div className="pathway-toolbar"><Input aria-label={t('Search pathways')} placeholder={t('Search pathways')} value={search} onChange={e=>setSearch(e.target.value)}/><Button className="blue-button" onClick={()=>{setDraft(empty());setMode('any');setCourseSearch('');}}>{t('Create pathway')}</Button></div>
 {draft?<section className="paper pathway-panel"><h2>{t(draft.id?'Edit pathway':'Create pathway')}</h2><form onSubmit={async e=>{e.preventDefault();if(await post({...draft,id:draft.id||undefined,action:'save'})){setDraft(null);setNotice(t('Pathway saved. Existing assignments keep their original requirements.'));}}}><fieldset disabled={busy}>
 <div className="pathway-fields"><label>{t('Pathway name')}<Input required maxLength={150} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>{t('Deadline (days from assignment)')}<Input type="number" min={1} max={3650} value={draft.deadline_days??''} placeholder={t('No deadline')} onChange={e=>setDraft({...draft,deadline_days:e.target.value?Number(e.target.value):null})}/></label></div>
 <label>{t('Description')}<textarea maxLength={2000} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label>
 <div className="pathway-fields"><label>{t('Course order')}<NativeSelect value={mode} onChange={e=>{setMode(e.target.value);setDraft({...draft,items:ordered(draft.items,e.target.value)});}}><option value="any">{t('Any order')}</option><option value="sequence">{t('In sequence')}</option><option value="first">{t('First course, then any order')}</option><option value="stages">{t('Custom stages')}</option></NativeSelect></label><div><label className="pathway-check"><input type="checkbox" checked={draft.award_certificate} onChange={e=>setDraft({...draft,award_certificate:e.target.checked})}/>{t('Award a pathway certificate')}</label><label className="pathway-check"><input type="checkbox" checked={draft.archived} onChange={e=>setDraft({...draft,archived:e.target.checked})}/>{t('Archive pathway')}</label></div></div>
 <p>{t('Complete every course in a stage before the next stage opens. Courses in the same stage can be taken in any order.')}</p>
 <ol className="pathway-course-list">{draft.items.map((item,index)=><li key={item.courseId}><span><strong>{data.courses?.find(c=>c.id===item.courseId)?.title||item.courseId}</strong><small>{t('Stage')} {item.stage}</small></span>{mode==='stages'&&<label>{t('Stage')}<Input type="number" min={1} max={100} value={item.stage} onChange={e=>setDraft({...draft,items:draft.items.map((i,n)=>n===index?{...i,stage:Number(e.target.value)}:i)})}/></label>}<div className="pathway-actions"><Button type="button" variant="outline" aria-label={t('Move course up')} disabled={!index} onClick={()=>{const items=[...draft.items];[items[index-1],items[index]]=[items[index],items[index-1]];setDraft({...draft,items:ordered(items)});}}>↑</Button><Button type="button" variant="outline" aria-label={t('Move course down')} disabled={index===draft.items.length-1} onClick={()=>{const items=[...draft.items];[items[index+1],items[index]]=[items[index],items[index+1]];setDraft({...draft,items:ordered(items)});}}>↓</Button><Button type="button" variant="outline" onClick={()=>setDraft({...draft,items:ordered(draft.items.filter((_,n)=>n!==index))})}>{t('Remove')}</Button></div></li>)}</ol>
 <label>{t('Add courses')}<Input placeholder={t('Search courses')} value={courseSearch} onChange={e=>setCourseSearch(e.target.value)}/></label><div className="pathway-options">{data.courses?.filter(c=>!draft.items.some(i=>i.courseId===c.id)&&c.title.toLowerCase().includes(courseSearch.toLowerCase())).map(c=><button type="button" key={c.id} onClick={()=>setDraft({...draft,items:ordered([...draft.items,{courseId:c.id,stage:1}])})}>+ {c.title}</button>)}</div>
 <p>{t('Valid completed courses count automatically. Existing assignments are reused. New course assignments follow the organisation’s credit settings.')}</p>
 <div className="pathway-actions"><Button className="blue-button" disabled={!draft.items.length}>{t(busy?'Saving…':'Save pathway')}</Button><Button type="button" variant="outline" onClick={()=>setDraft(null)}>{t('Cancel')}</Button></div>
 </fieldset></form></section>:<div className="pathway-grid">{data.pathways?.filter(p=>p.name.toLowerCase().includes(search.toLowerCase())).map(p=><article className="paper pathway-panel" key={p.id}><span className="eyebrow">{t(p.archived?'Archived':'Active')} · {p.items.length} {t('Courses')}</span><h2>{p.name}</h2><p>{p.description}</p><p>{p.deadline_days?t('{days} days from assignment',{days:p.deadline_days}):t('No deadline')} · {t(p.award_certificate?'Pathway certificate':'Course certificates only')}</p><div className="pathway-actions"><Button variant="outline" onClick={()=>edit(p)}>{t('Edit')}</Button>{!p.archived&&<Button className="blue-button" onClick={()=>{setPathwayId(p.id);setTab('assign');}}>{t('Assign pathway')}</Button>}</div></article>)}{!data.pathways?.length&&<p>{t('Create your first pathway to group courses into a programme.')}</p>}</div>}
 </>}
 {data?.enabled&&tab==='assign'&&<section className="paper pathway-panel"><h2>{t('Assign pathway')}</h2><form onSubmit={async e=>{e.preventDefault();const d=await post({action:'assign',pathwayId,learnerIds:selected.map(p=>p.id),dueDate});if(d){setNotice(t('{assigned} assigned · {existing} already assigned',{assigned:d.assigned,existing:d.existing}));setSelected([]);}}}><fieldset disabled={busy}><div className="pathway-fields"><label>{t('Pathway')}<NativeSelect required value={pathwayId} onChange={e=>setPathwayId(e.target.value)}><option value="">{t('Choose pathway')}</option>{data.pathways?.filter(p=>!p.archived).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</NativeSelect></label><label>{t('Fixed completion deadline (optional)')}<Input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label></div><p>{t('Leave the fixed deadline blank to use the pathway’s days from assignment. Earlier course deadlines are retained.')}</p>
 <label>{t('Find learners')}<Input placeholder={t('Search name, email or Workday ID')} value={personSearch} onChange={e=>setPersonSearch(e.target.value)}/></label><div className="pathway-options">{people.slice(0,50).map(p=><label className="pathway-check" key={p.id}><input type="checkbox" checked={selected.some(s=>s.id===p.id)} onChange={e=>setSelected(e.target.checked?[...selected,p]:selected.filter(s=>s.id!==p.id))}/><span>{p.name} · {p.email||p.workday_id} · {p.country}</span></label>)}</div>{people.length>50&&<p>{t('More learners match. Refine your search.')}</p>}<p>{selected.length} {t('learners selected')}</p><div className="pathway-selected">{selected.map(p=><Button type="button" variant="outline" key={p.id} onClick={()=>setSelected(selected.filter(s=>s.id!==p.id))}>{p.name} ×</Button>)}</div>
 <p>{t('All selected learners are assigned together. If a course is unavailable or credits are insufficient, no assignments are saved.')}</p><Button className="blue-button" disabled={!pathwayId||!selected.length||selected.length>100}>{t(busy?'Assigning…':'Assign pathway')}</Button></fieldset></form></section>}
 </main></div>;
}
